#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "ye tu",
                "name":        "Ò°ÍÃ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xueshan/npc/yetu.c",
        ]),
        ([
                "id":          "mu jiang",
                "name":        "Ä¾½³",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xiangyang/npc/mujiang.c",
        ]),
        ([
                "id":          "jin xier",
                "name":        "½øÏ²¶ù",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/xier.c",
        ]),
        ([
                "id":          "lao shu",
                "name":        "ÀÏÊó",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/ad-laoshu.c",
        ]),
        ([
                "id":          "tong",
                "name":        "Ð¡µÀÍ¯",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/quanzhen/npc/daotong1.c",
        ]),
        ([
                "id":          "lamb",
                "name":        "[1;33mÒ°»ÆÑò[2;37;0m",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/clone/quarry/yang3.c",
        ]),
        ([
                "id":          "fortune teller",
                "name":        "ÀîÌú×ì",
                "type":        "É±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/huashan/npc/teller.c",
        ]),
        ([
                "id":          "heersu",
                "name":        "ºÕ¶ûËÕ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/guanwai/npc/heersu.c",
        ]),
        ([
                "id":          "meihua cilu",
                "name":        "[33mÃ·»¨´ÆÂ¹[2;37;0m",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/clone/quarry/lu3.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "¼Ò¶¡",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/foshan/npc/jiading.c",
        ]),
        ([
                "id":          "bee",
                "name":        "ÃÛ·ä",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/foshan/npc/bee.c",
        ]),
        ([
                "id":          "seller",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/emei/npc/xiao-fan.c",
        ]),
        ([
                "id":          "little monkey",
                "name":        "Ð¡ºï",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/emei/npc/little_monkey.c",
        ]),
        ([
                "id":          "big frog",
                "name":        "[32m´óÇàÍÜ[2;37;0m",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/emei/npc/frog.c",
        ]),
        ([
                "id":          "bianfu",
                "name":        "òùòð",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/clone/quarry/fu.c",
        ]),
        ([
                "id":          "xiao lama",
                "name":        "Ð¡À®Âï",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xueshan/npc/x_lama.c",
        ]),
        ([
                "id":          "dipi",
                "name":        "µØÆ¦",
                "type":        "É±",
                "bonus":       48,
                "msg":        "",
                "object":      "/d/village/npc/dipi.c",
        ]),
        ([
                "id":          "laonian sengren",
                "name":        "ÀÏÄêÉ®ÈË",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/laoniansengren.c",
        ]),
        ([
                "id":          "punk",
                "name":        "Ð¡Á÷Ã¥",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hanzhong/npc/punk.c",
        ]),
        ([
                "id":          "lin pingzhi",
                "name":        "ÁÖÆ½Ö®",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/huashan/npc/lin-pingzhi.c",
        ]),
        ([
                "id":          "huoji",
                "name":        "»ï¼Æ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/huanghe/npc/huoji.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/henshan/npc/xiaoer2.c",
        ]),
        ([
                "id":          "lao zhe",
                "name":        "ÀÏÕß",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/heimuya/npc/laozhe.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "ÊéÉú",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/shu-sheng.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "ÊéÉú",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/shu-sheng.c",
        ]),
        ([
                "id":          "punk",
                "name":        "Ð¡Á÷Ã¥",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/village/npc/punk.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "Ò©ÆÌ»ï¼Æ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/suzhou/npc/huoji.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "¼Ò¶¡",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/henshan/npc/jiading.c",
        ]),
        ([
                "id":          "jiao tu",
                "name":        "ÈÕÔÂÉñ½Ì½ÌÍ½",
                "type":        "É±",
                "bonus":       48,
                "msg":        "",
                "object":      "/d/heimuya/npc/jiaotu.c",
        ]),
        ([
                "id":          "yufeng",
                "name":        "[1;37mÓñ·ä[2;37;0m",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/gumu/npc/yufeng.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer3.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "yahuan",
                "name":        "Ñ¾»·",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/yanziwu/npc/yahuan.c",
        ]),
        ([
                "id":          "nan pu",
                "name":        "ÄÐÆÍ",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/yanziwu/npc/nanpu.c",
        ]),
        ([
                "id":          "sha chong",
                "name":        "É³³æ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xingxiu/npc/shachong.c",
        ]),
        ([
                "id":          "shudian laoban",
                "name":        "ÊéµêÀÏ°å",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/xiangyang/npc/shudianboss.c",
        ]),
        ([
                "id":          "shaofan shifu",
                "name":        "ÉÕ·¹Ê¦¸µ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xiangyang/npc/shaofanshifu.c",
        ]),
        ([
                "id":          "zhong ling",
                "name":        "ÖÓÁé",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/zhongling.c",
        ]),
        ([
                "id":          "bee",
                "name":        "ÃÛ·ä",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/bee.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "Ìô·ò",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taishan/npc/tiao-fu.c",
        ]),
        ([
                "id":          "ni gu",
                "name":        "Äá¹Ã",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/nigu2.c",
        ]),
        ([
                "id":          "ni gu",
                "name":        "Äá¹Ã",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/nigu1.c",
        ]),
        ([
                "id":          "ban jiu",
                "name":        "°ßð¯",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/clone/quarry/niao.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xueshan/npc/xiaoer2.c",
        ]),
        ([
                "id":          "ye tu",
                "name":        "Ò°ÍÃ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/yetu.c",
        ]),
        ([
                "id":          "tufei",
                "name":        "ÍÁ·Ë",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wudang/npc/tufei2.c",
        ]),
        ([
                "id":          "wang xiaoer",
                "name":        "ÍõÐ¡¶þ",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/village/npc/wang.c",
        ]),
        ([
                "id":          "lao shu",
                "name":        "ÀÏÊó",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/ad-laoshu.c",
        ]),
        ([
                "id":          "seller",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/quanzhen/npc/seller.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "¼Ò¶¡",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hanzhong/npc/jiading.c",
        ]),
        ([
                "id":          "dipi",
                "name":        "µØÆ¦",
                "type":        "É±",
                "bonus":       48,
                "msg":        "",
                "object":      "/d/hanzhong/npc/dipi.c",
        ]),
        ([
                "id":          "tong",
                "name":        "µÀÍ¯",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/quanzhen/npc/daotong.c",
        ]),
        ([
                "id":          "zhangfang",
                "name":        "ÕÊ·¿ÏÈÉú",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/lingzhou/npc/zhangfang.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "wu gong",
                "name":        "[1;31mòÚò¼[2;37;0m",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/huanghe/npc/wugong.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xiangyang/npc/xiaoer2.c",
        ]),
        ([
                "id":          "monkey",
                "name":        "ºï×Ó",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wudang/npc/monkey.c",
        ]),
        ([
                "id":          "lao qiao",
                "name":        "ÇÇÈý»±",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/lao-qiao.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/quanzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "kid",
                "name":        "Ð¡º¢",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/heimuya/npc/kid.c",
        ]),
        ([
                "id":          "duan tiande",
                "name":        "¶ÎÌìµÂ",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guiyun/npc/duantiande.c",
        ]),
        ([
                "id":          "xiu cai",
                "name":        "ÂäµÚÐã²Å",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiucai.c",
        ]),
        ([
                "id":          "haoshou",
                "name":        "ÐÇËÞÅÉºÅÊÖ",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/xingxiu/npc/haoshou.c",
        ]),
        ([
                "id":          "xiao tufei",
                "name":        "Ð¡ÍÁ·Ë",
                "type":        "É±",
                "bonus":       48,
                "msg":        "",
                "object":      "/d/wudang/npc/xiao_tufei.c",
        ]),
        ([
                "id":          "wuya",
                "name":        "ÎÚÑ»",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/quanzhou/npc/wuya.c",
        ]),
        ([
                "id":          "sheep",
                "name":        "Ò°Ñò",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/mingjiao/npc/sheep.c",
        ]),
        ([
                "id":          "zhang",
                "name":        "â¯",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/clone/quarry/zhang.c",
        ]),
        ([
                "id":          "wolf dog",
                "name":        "´óÀÇ¹·",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/wolfdog.c",
        ]),
        ([
                "id":          "lao ban",
                "name":        "¾Æ¹ÝÀÏ°å",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/guanwai/npc/laoban.c",
        ]),
        ([
                "id":          "seller",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaofan.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "zhang chaotang",
                "name":        "ÕÅ³¯ÌÆ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/foshan/npc/zhang.c",
        ]),
        ([
                "id":          "wolf dog",
                "name":        "´óÀÇ¹·",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/clone/quarry/gou2.c",
        ]),
        ([
                "id":          "shou shangren",
                "name":        "ÊÝÉÌÈË",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/foshan/npc/shou.c",
        ]),
        ([
                "id":          "pang shangren",
                "name":        "ÅÖÉÌÈË",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/foshan/npc/pang.c",
        ]),
        ([
                "id":          "feng qi",
                "name":        "·ïÆß",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/foshan/npc/fengqi.c",
        ]),
        ([
                "id":          "hudie",
                "name":        "ºûµû",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/yanziwu/npc/hudie.c",
        ]),
        ([
                "id":          "du zhizhu",
                "name":        "[1;34m¶¾Ö©Öë[2;37;0m",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xuedao/npc/zhizhu.c",
        ]),
        ([
                "id":          "girl",
                "name":        "Î¬Îá¶ûÉÙÅ®",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xingxiu/npc/shaonv.c",
        ]),
        ([
                "id":          "wuya",
                "name":        "ÎÚÑ»",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/wuya.c",
        ]),
        ([
                "id":          "little bee",
                "name":        "Ð¡ÃÛ·ä",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/little_bee.c",
        ]),
        ([
                "id":          "duck",
                "name":        "Ò°Ñ¼",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/duck.c",
        ]),
        ([
                "id":          "cui hua",
                "name":        "´ä»¨",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/village/npc/cuihua.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-er2.c",
        ]),
        ([
                "id":          "jingxiang ke",
                "name":        "½øÏã¿Í",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiang-ke.c",
        ]),
        ([
                "id":          "jinxiang ke",
                "name":        "½øÏã¿Í",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xueshan/npc/xiang-ke.c",
        ]),
        ([
                "id":          "bee",
                "name":        "ÃÛ·ä",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/bee.c",
        ]),
        ([
                "id":          "monkey",
                "name":        "ºï×Ó",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/mingjiao/npc/monkey.c",
        ]),
        ([
                "id":          "wuya",
                "name":        "ÎÚÑ»",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/wuya.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "Ìô·ò",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/tiao-fu.c",
        ]),
        ([
                "id":          "qianlong",
                "name":        "Ç¬Â¡»ÊµÛ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/qianlong.c",
        ]),
        ([
                "id":          "maque",
                "name":        "ÂéÈ¸",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/maque.c",
        ]),
        ([
                "id":          "liu mang",
                "name":        "Á÷Ã¥",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/liumang.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "¼Ò¶¡",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/npc/jiading.c",
        ]),
        ([
                "id":          "girl",
                "name":        "²É²èÅ®",
                "type":        "É±",
                "bonus":       47,
                "msg":        "",
                "object":      "/d/hangzhou/npc/caichanu.c",
        ]),
        ([
                "id":          "xiao lama",
                "name":        "Ð¡À®Âï",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xuedao/npc/x_lama.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/taishan/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/suzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/suzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "liu mang",
                "name":        "Á÷Ã¥",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/liumang.c",
        ]),
        ([
                "id":          "liu furen",
                "name":        "Áõ·òÈË",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/henshan/npc/liufuren.c",
        ]),
        ([
                "id":          "wolf2",
                "name":        "ÀÇ",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/heimuya/npc/wolf.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "pihuo shang",
                "name":        "Æ¤»õÉÌ",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/guanwai/npc/pihuoshang.c",
        ]),
        ([
                "id":          "meihua xionglu",
                "name":        "[33mÃ·»¨ÐÛÂ¹[2;37;0m",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/guanwai/npc/buck.c",
        ]),
        ([
                "id":          "gushou",
                "name":        "ÐÇËÞÅÉ¹ÄÊÖ",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xingxiu/npc/gushou.c",
        ]),
        ([
                "id":          "boshou",
                "name":        "ÐÇËÞÅÉîàÊÖ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xingxiu/npc/boshou.c",
        ]),
        ([
                "id":          "xiao louluo",
                "name":        "Ð¡à¶ÂÞ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/xiao_louluo.c",
        ]),
        ([
                "id":          "dog",
                "name":        "Ò°¹·",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/clone/quarry/gou.c",
        ]),
        ([
                "id":          "seller",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/suzhou/npc/seller.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-er.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "Ìô·ò",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/tiao-fu.c",
        ]),
        ([
                "id":          "lao shu",
                "name":        "ÀÏÊó",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/ad-laoshu.c",
        ]),
        ([
                "id":          "song shu",
                "name":        "ËÉÊó",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/clone/quarry/song.c",
        ]),
        ([
                "id":          "meihua lu",
                "name":        "Ã·»¨Â¹",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/clone/quarry/lu.c",
        ]),
        ([
                "id":          "eagle",
                "name":        "ÍºÓ¥",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/clone/quarry/ying.c",
        ]),
        ([
                "id":          "woman",
                "name":        "Î¬Îá¶û×å¸¾Å®",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xingxiu/npc/woman.c",
        ]),
        ([
                "id":          "wang yuyan",
                "name":        "ÍõÓïæÌ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xiaoyao/npc/wangyuyan.c",
        ]),
        ([
                "id":          "little monkey",
                "name":        "Ð¡ºï",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/little_monkey.c",
        ]),
        ([
                "id":          "lai fuer",
                "name":        "À´¸£¶ù",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/fuer.c",
        ]),
        ([
                "id":          "seller",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/village/npc/seller.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "ÊéÉú",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/taishan/npc/shu-sheng.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hanzhong/npc/xiaoer1.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hanzhong/npc/xiaoer.c",
        ]),
        ([
                "id":          "wu gui",
                "name":        "ÎÚ¹ê",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/wugui.c",
        ]),
        ([
                "id":          "wolf dog",
                "name":        "´óÀÇ¹·",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/clone/quarry/gou2.c",
        ]),
        ([
                "id":          "chu shi",
                "name":        "³øÊ¦",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/meizhuang/npc/chushi.c",
        ]),
        ([
                "id":          "da han",
                "name":        "´óºº",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/huanghe/npc/bangzong.c",
        ]),
        ([
                "id":          "ye tu",
                "name":        "Ò°ÍÃ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/yetu.c",
        ]),
        ([
                "id":          "xue laoban",
                "name":        "Ñ¦ÀÏ°å",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/xueboss.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/xiaoer.c",
        ]),
        ([
                "id":          "danding he",
                "name":        "[1;31mµ¤[2;37;0m¶¥º×",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/xianhe.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "ÎÚÒÄÉÌ··",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/wshangfan.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "Ì¨ÒÄÉÌ··",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/tshangfan.c",
        ]),
        ([
                "id":          "tai jian",
                "name":        "Ì«¼à",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/taijian.c",
        ]),
        ([
                "id":          "maque",
                "name":        "ÂéÈ¸",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/maque.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "Ì¨ÒÄÉÌ··",
                "type":        "É±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/dali/npc/bshangfan.c",
        ]),
        ([
                "id":          "dufeng",
                "name":        "¶¾·ä",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/bee.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/chengdu/npc/xiaoer2.c",
        ]),
        ([
                "id":          "yaodian huoji",
                "name":        "Ò©µê»ï¼Æ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/chengdu/npc/huoji.c",
        ]),
        ([
                "id":          "xiao guizi",
                "name":        "Ð¡¹ð×Ó",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/xiaoguiz.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/city/npc/xiaoer.c",
        ]),
        ([
                "id":          "wolf dog",
                "name":        "´óÀÇ¹·",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/wolfdog.c",
        ]),
        ([
                "id":          "liu mang",
                "name":        "Á÷Ã¥",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/liumang.c",
        ]),
        ([
                "id":          "li apo",
                "name":        "Àî°¢ÆÅ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/city/npc/liapo.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "¼Ò¶¡",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/city/npc/jiading.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "Ò©ÆÌ»ï¼Æ",
                "type":        "É±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/city/npc/huoji2.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "Ò©ÆÌ»ï¼Æ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/city/npc/huoji.c",
        ]),
        ([
                "id":          "xiao hunhun",
                "name":        "Ð¡»ì»ì",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/city/npc/hunhun.c",
        ]),
        ([
                "id":          "zi yi",
                "name":        "[35m×ÏÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/ziyi.c",
        ]),
        ([
                "id":          "qing yi",
                "name":        "[1;36mÇàÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/qingyi.c",
        ]),
        ([
                "id":          "lv yi",
                "name":        "[1;32mÂÌÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/luyi.c",
        ]),
        ([
                "id":          "lan yi",
                "name":        "[1;34mÀ¶ÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/lanyi.c",
        ]),
        ([
                "id":          "ji nu",
                "name":        "¼ËÅ®",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/jinu.c",
        ]),
        ([
                "id":          "huang yi",
                "name":        "[1;33m»ÆÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/huangyi.c",
        ]),
        ([
                "id":          "hong yi",
                "name":        "[1;31mºìÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/hongyi.c",
        ]),
        ([
                "id":          "fen yi",
                "name":        "[1;35m·ÛÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/fenyi.c",
        ]),
        ([
                "id":          "shi jiugong",
                "name":        "Ê±¾Å¹«",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/doctor.c",
        ]),
        ([
                "id":          "bai yi",
                "name":        "[1;37m°×ÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/baiyi.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/beijing/npc/xiaoer.c",
        ]),
        ([
                "id":          "du she",
                "name":        "¶¾Éß",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/beijing/npc/liandan_dushe.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/baituo/npc/xiaoer.c",
        ]),
        ([
                "id":          "white lady",
                "name":        "°×ÒÂÉÙÅ®",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/whitelady.c",
        ]),
        ([
                "id":          "shi wei",
                "name":        "ÊËÎÀ",
                "type":        "É±",
                "bonus":       76,
                "msg":        "",
                "object":      "/d/baituo/npc/shiwei.c",
        ]),
        ([
                "id":          "xiao shanzei",
                "name":        "Ð¡É½Ôô",
                "type":        "É±",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/baituo/npc/shanzei1.c",
        ]),
        ([
                "id":          "kid",
                "name":        "Ð¡º¢",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/baituo/npc/kid.c",
        ]),
        ([
                "id":          "bai tu",
                "name":        "°×ÍÃ",
                "type":        "É±",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/baituo/npc/baitu.c",
        ]),
        ([
                "id":          "zhao gouer",
                "name":        "ÕÔ¹·¶ù",
                "type":        "É±",
                "bonus":       65,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/zhao-gouer.c",
        ]),
        ([
                "id":          "hong niang",
                "name":        "ºìÄï",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/adm/npc/hongniang.c",
        ]),
});
mapping query_questdg()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
string *get_questname()
{
        int i;
        string *result = ({});
        
        for (i = 0; i < sizeof(quest);i ++)
                result += ({ quest[i]["name"] });
                
        return result;
}

