#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "jiuyi daoren",
                "name":        "¾ÅÒíµÀÈË",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/lingjiu/npc/jiuyi.c",
        ]),
        ([
                "id":          "wu santong",
                "name":        "ÎäÈýÍ¨",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wusantong.c",
        ]),
        ([
                "id":          "wang bashuai",
                "name":        "Íõ°ËË¥",
                "type":        "É±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/wang8.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "Ã½ÆÅ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/suzhou/npc/meipo.c",
        ]),
        ([
                "id":          "sha tianjiang",
                "name":        "É³Ìì½­",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/songshan/npc/sha.c",
        ]),
        ([
                "id":          "yue lingshan",
                "name":        "ÔÀÁéÉº",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huashan/npc/yue-lingshan.c",
        ]),
        ([
                "id":          "hou tonghai",
                "name":        "ºîÍ¨º£",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huanghe/npc/hou.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "°×ÒÂÎäÊ¿",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi1.c",
        ]),
        ([
                "id":          "di xiu",
                "name":        "µÒÐÞ",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/songshan/di.c",
        ]),
        ([
                "id":          "yu renhao",
                "name":        "ÓÚÈËºÀ",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/yu.c",
        ]),
        ([
                "id":          "san hu",
                "name":        "ºöÂ×Èý»¢",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sanhu.c",
        ]),
        ([
                "id":          "jiao wenqi",
                "name":        "½¹ÎÄÆÚ",
                "type":        "É±",
                "bonus":       99,
                "msg":        "",
                "object":      "/d/guanwai/npc/jiaowenqi.c",
        ]),
        ([
                "id":          "zu qianqiu",
                "name":        "×æÇ§Çï",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huanghe/npc/zu.c",
        ]),
        ([
                "id":          "er hu",
                "name":        "ºöÂ×¶þ»¢",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/erhu.c",
        ]),
        ([
                "id":          "da hu",
                "name":        "ºöÂ×´ó»¢",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/dahu.c",
        ]),
        ([
                "id":          "bo chen",
                "name":        "²·³Á",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/songshan/npc/bo.c",
        ]),
        ([
                "id":          "lao denuo",
                "name":        "ÀÍµÂÅµ",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/huashan/npc/lao-denuo.c",
        ]),
        ([
                "id":          "sun popo",
                "name":        "ËïÆÅÆÅ",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/gumu/npc/sun.c",
        ]),
        ([
                "id":          "hong renxiong",
                "name":        "ºéÈËÐÛ",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/hong.c",
        ]),
        ([
                "id":          "song qingshu",
                "name":        "ËÎÇàÊé",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/emei/npc/songqingshu.c",
        ]),
        ([
                "id":          "wu xiuwen",
                "name":        "ÎäÐÞÎÄ",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wuxiuwen.c",
        ]),
        ([
                "id":          "zhou wushu",
                "name":        "ÖÜÎåÊä",
                "type":        "É±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhou5.c",
        ]),
        ([
                "id":          "zheng qimie",
                "name":        "Ö£ÆßÃð",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zheng7.c",
        ]),
        ([
                "id":          "lu bai",
                "name":        "Â½°Ø",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/songshan/npc/lu.c",
        ]),
        ([
                "id":          "gao kexin",
                "name":        "¸ß¿ËÐÂ",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/songshan/npc/gao.c",
        ]),
        ([
                "id":          "sun sanhui",
                "name":        "ËïÈý»Ù",
                "type":        "É±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/sun3.c",
        ]),
        ([
                "id":          "yuji zi",
                "name":        "Óñçá×Ó",
                "type":        "É±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yujizi.c",
        ]),
        ([
                "id":          "zhong zhen",
                "name":        "ÖÓÕò",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/songshan/npc/zhong.c",
        ]),
        ([
                "id":          "luo renjie",
                "name":        "ÂÞÈË½Ü",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/luo.c",
        ]),
        ([
                "id":          "zhu ziliu",
                "name":        "Öì×ÓÁø",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/zhuziliu.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "ºìÒÂÎäÊ¿",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi2.c",
        ]),
        ([
                "id":          "li kexiu",
                "name":        "Àî¿ÉÐã",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/hangzhou/npc/likexiu.c",
        ]),
        ([
                "id":          "si hu",
                "name":        "ºöÂ×ËÄ»¢",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sihu.c",
        ]),
        ([
                "id":          "yuqing zi",
                "name":        "Óñíà×Ó",
                "type":        "É±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yuqingzi.c",
        ]),
        ([
                "id":          "ding mian",
                "name":        "¶¡Ãã",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/songshan/npc/ding.c",
        ]),
        ([
                "id":          "huo renying",
                "name":        "ºîÈËÓ¢",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/hou.c",
        ]),
        ([
                "id":          "hu qingniu",
                "name":        "ºúÇàÅ£",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/mingjiao/npc/hu.c",
        ]),
        ([
                "id":          "li si",
                "name":        "ÀîËÄ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/village/npc/xiejian.c",
        ]),
        ([
                "id":          "zhao yishang",
                "name":        "ÕÔÒ»ÉË",
                "type":        "É±",
                "bonus":       62,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhao1.c",
        ]),
        ([
                "id":          "li sicui",
                "name":        "ÀîËÄ´Ý",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/li4.c",
        ]),
        ([
                "id":          "yuyin zi",
                "name":        "ÓñÒô×Ó",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yuyinzi.c",
        ]),
        ([
                "id":          "tang yinghu",
                "name":        "ÌÀÓ¢ðÀ",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/songshan/npc/tang.c",
        ]),
        ([
                "id":          "ping si",
                "name":        "Æ½ËÄ",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/hu/pingsi.c",
        ]),
        ([
                "id":          "huo xiansheng",
                "name":        "»ôÏÈÉú",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/dali/npc/huo.c",
        ]),
        ([
                "id":          "yulin jun",
                "name":        "ÓùÁÖ¾ü",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/d/changan/npc/yulinjun.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "Îä½«",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/wujiang.c",
        ]),
        ([
                "id":          "murong hao",
                "name":        "Ä½ÈÝºÀ",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/changan/npc/murong-hao.c",
        ]),
        ([
                "id":          "da shou",
                "name":        "´òÊÖ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/dashou.c",
        ]),
        ([
                "id":          "bao biao",
                "name":        "ÈºÓñÂ¥±£ïÚ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/baobiao.c",
        ]),
        ([
                "id":          "gongtangcang guoshi",
                "name":        "¹±ÌÆ²Ö¹úÊ¦",
                "type":        "É±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/guoshi.c",
        ]),
        ([
                "id":          "shan yong",
                "name":        "ÉÆÓÂ",
                "type":        "É±",
                "bonus":       61,
                "msg":        "",
                "object":      "/kungfu/class/xuedao/shanyong.c",
        ]),
        ([
                "id":          "xue muhua",
                "name":        "Ñ¦Ä½»ª",
                "type":        "É±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/xuemuh.c",
        ]),
        ([
                "id":          "zhao zhijing",
                "name":        "ÕÔÖ¾¾´",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/zhao.c",
        ]),
        ([
                "id":          "kuai huosan",
                "name":        "¿ì»îÈý",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/kuai-huosan.c",
        ]),
        ([
                "id":          "jiang shangyou",
                "name":        "½­ÉÏÓÎ",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/jiang-sy.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "Ã½ÆÅ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/adm/npc/meipo.c",
        ]),
});
mapping query_questdg()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
