#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "liang ziwen",
                "name":        "Áº×ÓÎÌ",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/huanghe/npc/liang.c",
        ]),
        ([
                "id":          "shang sanniang",
                "name":        "É£ÈýÄï",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/heimuya/npc/shang.c",
        ]),
        ([
                "id":          "jiao wenqi",
                "name":        "½¹ÎÄÆÚ",
                "type":        "É±",
                "bonus":       58,
                "msg":        "",
                "object":      "/d/guanwai/npc/jiaowenqi.c",
        ]),
        ([
                "id":          "zhang seng",
                "name":        "ÕÈÉ®",
                "type":        "É±",
                "bonus":       86,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/18jingang-4zhang.c",
        ]),
        ([
                "id":          "sha tongtian",
                "name":        "É³Í¨Ìì",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/huanghe/npc/sha.c",
        ]),
        ([
                "id":          "chu yuan",
                "name":        "ñÒÔ²",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/hangzhou/npc/chuyuan.c",
        ]),
        ([
                "id":          "xiao yuanshan",
                "name":        "ÏôÔ¶É½",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiaoyuanshan.c",
        ]),
        ([
                "id":          "tongbai xiong",
                "name":        "Í¯°ÙÐÜ",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/heimuya/npc/tongbw.c",
        ]),
        ([
                "id":          "jia bu",
                "name":        "¼Ö²¼",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/heimuya/npc/jiabu.c",
        ]),
        ([
                "id":          "tian boguang",
                "name":        "Ìï²®¹â",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/henshan/npc/tian.c",
        ]),
        ([
                "id":          "wang cheng",
                "name":        "Íõ³Ï",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/heimuya/npc/wangcheng.c",
        ]),
        ([
                "id":          "long jun",
                "name":        "Áú¿¥",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/npc/longjun.c",
        ]),
        ([
                "id":          "hu qingyu",
                "name":        "ºúÇìÓà",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/npc/huqingyu.c",
        ]),
        ([
                "id":          "shangguan yun",
                "name":        "ÉÏ¹ÙÔÆ",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/heimuya/npc/shanggy.c",
        ]),
        ([
                "id":          "teng yilei",
                "name":        "ëøÒ»À×",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/guanwai/npc/tengyilei.c",
        ]),
        ([
                "id":          "bo seng",
                "name":        "îàÉ®",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/18jingang-4bo.c",
        ]),
        ([
                "id":          "peng lianhu",
                "name":        "ÅíÁ¬»¢",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/huanghe/npc/peng.c",
        ]),
        ([
                "id":          "deng banian",
                "name":        "µË°ËÄê",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/songshan/npc/deng.c",
        ]),
        ([
                "id":          "ren yingying",
                "name":        "ÈÎÓ¯Ó¯",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/huashan/npc/ren-yingying.c",
        ]),
        ([
                "id":          "ouyang ke",
                "name":        "Å·Ñô¿Ë",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/ouyang/ouyangke.c",
        ]),
        ([
                "id":          "cheng lingsu",
                "name":        "³ÌÁéËØ",
                "type":        "É±",
                "bonus":       97,
                "msg":        "",
                "object":      "/kungfu/class/hu/cheng.c",
        ]),
        ([
                "id":          "xiao qun",
                "name":        "ÏôÈº",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/tongling2.c",
        ]),
        ([
                "id":          "zhang heng",
                "name":        "ÕÅºâ",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/tongling1.c",
        ]),
        ([
                "id":          "li",
                "name":        "Àî¹Ü¼Ò",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/baituo/npc/li.c",
        ]),
        ([
                "id":          "samu huofo",
                "name":        "ÈøÄ¾»î·ð",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/samu.c",
        ]),
        ([
                "id":          "lingzhi shangren",
                "name":        "ÁéÖÇÉÏÈË",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/lingzhi.c",
        ]),
        ([
                "id":          "jiamu huofo",
                "name":        "¼ÎÄ¾»î·ð",
                "type":        "É±",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/jiamu.c",
        ]),
        ([
                "id":          "daerba huofo",
                "name":        "´ï¶û°Í",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/daerba.c",
        ]),
        ([
                "id":          "bao xiang",
                "name":        "±¦Ïó",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/xuedao/baoxiang.c",
        ]),
        ([
                "id":          "zhaixing zi",
                "name":        "ÕªÐÇ×Ó",
                "type":        "É±",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/xingxiu/zhaixing.c",
        ]),
        ([
                "id":          "shihou zi",
                "name":        "Ê¨ºð×Ó",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/xingxiu/shihou.c",
        ]),
        ([
                "id":          "chuchen zi",
                "name":        "³ö³¾×Ó",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/xingxiu/chuchen.c",
        ]),
        ([
                "id":          "song qingshu",
                "name":        "ËÎÇàÊé",
                "type":        "É±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/wudang/xiaosong.c",
        ]),
        ([
                "id":          "huang rong",
                "name":        "»ÆÈØ",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/taohua/rong.c",
        ]),
        ([
                "id":          "yin jin",
                "name":        "Òó½õ",
                "type":        "É±",
                "bonus":       92,
                "msg":        "",
                "object":      "/kungfu/class/shenlong/yin.c",
        ]),
        ([
                "id":          "lu gaoxuan",
                "name":        "Â½¸ßÐù",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shenlong/lu.c",
        ]),
        ([
                "id":          "li mochou",
                "name":        "ÀîÄª³î",
                "type":        "É±",
                "bonus":       97,
                "msg":        "",
                "object":      "/kungfu/class/gumu/li.c",
        ]),
        ([
                "id":          "zuo quan",
                "name":        "×óÈ«",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/zuo-qu.c",
        ]),
        ([
                "id":          "ma juwei",
                "name":        "Âí¾ãÎª",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/ma-jw.c",
        ]),
        ([
                "id":          "li futou",
                "name":        "Àî¸«Í·",
                "type":        "É±",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/li-futou.c",
        ]),
        ([
                "id":          "he bujing",
                "name":        "ºÎ²»¾»",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/he-bj.c",
        ]),
});
mapping query_questdg()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
