#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "xuelian",
                "name":        "ÌìÉ½Ñ©Á«",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/xuelian.c",
        ]),
        ([
                "id":          "piqiu",
                "name":        "Æ¤ôÃ",
                "type":        "Ñ°",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/guanwai/npc/obj/piqiu.c",
        ]),
        ([
                "id":          "zi pao",
                "name":        "×ÏÅÛ",
                "type":        "Ñ°",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/foshan/npc/obj/magcloth.c",
        ]),
        ([
                "id":          "red cloth",
                "name":        "[1;31mºìç±°À[2;37;0m",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/red_cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/fuzhou/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/emei/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/quanzhen/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/hangzhou/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "ÐåÃ·ÇàÒÂ",
                "type":        "Ñ°",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/meizhuang/npc/obj/qingyi.c",
        ]),
        ([
                "id":          "futou",
                "name":        "´ó¸«Í·",
                "type":        "Ñ°",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/futou.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/quanzhou/npc/obj/cloth.c",
        ]),
        ([
                "id":          "tonggu",
                "name":        "Í­¹Ä",
                "type":        "Ñ°",
                "bonus":       80,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/tonggu.c",
        ]),
        ([
                "id":          "pao",
                "name":        "»ÒÉ«µÀÅÛ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/wudang/obj/greyrobe.c",
        ]),
        ([
                "id":          "scarf",
                "name":        "[1;33mÐå»¨Ð¡·½½í[2;37;0m",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/xiu-scarf.c",
        ]),
        ([
                "id":          "moon-dress",
                "name":        "[1;37mÇí»¨ð¨ÔÂÉÑ[2;37;0m",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/moon-dress.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "[1;36mÇ³À¶É«Âí¹Ó[2;37;0m",
                "type":        "Ñ°",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/cloth.c",
        ]),
        ([
                "id":          "tonghao",
                "name":        "Í­ºÅ",
                "type":        "Ñ°",
                "bonus":       70,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/tonghao.c",
        ]),
        ([
                "id":          "tongbo",
                "name":        "Í­îà",
                "type":        "Ñ°",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/tongbo.c",
        ]),
        ([
                "id":          "dongbula",
                "name":        "¶¬²»À­",
                "type":        "Ñ°",
                "bonus":       65,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/dongbula.c",
        ]),
        ([
                "id":          "mini-ao",
                "name":        "[34m²Ê¶Ð½ôÉí°À[2;37;0m",
                "type":        "Ñ°",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/mini-dress.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       65,
                "msg1":        "",
                "object":      "/d/village/npc/obj/cloth.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "°×²¼ºÚ±ßôÂôÄ",
                "type":        "Ñ°",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/shaolin/obj/qing-cloth.c",
        ]),
        ([
                "id":          "yao qin",
                "name":        "ÑþÇÙ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/yaoqin.c",
        ]),
        ([
                "id":          "white cloth",
                "name":        "°×³ñÉÀ",
                "type":        "Ñ°",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/whitecloth1.c",
        ]),
        ([
                "id":          "da hui",
                "name":        "ÎÚÒÄ´ó÷â",
                "type":        "Ñ°",
                "bonus":       70,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/wdahui.c",
        ]),
        ([
                "id":          "tong qun",
                "name":        "Í²È¹",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/tongqun.c",
        ]),
        ([
                "id":          "duan qun",
                "name":        "Ì¨ÒÄ¶ÌÈ¹",
                "type":        "Ñ°",
                "bonus":       70,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/tduanqun.c",
        ]),
        ([
                "id":          "mao tan",
                "name":        "Ã«Ìº",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/maotan.c",
        ]),
        ([
                "id":          "ken ao",
                "name":        "Õ­ñÌ°À",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/kenao.c",
        ]),
        ([
                "id":          "kan dao",
                "name":        "¿³µ¶",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/kandao.c",
        ]),
        ([
                "id":          "pao",
                "name":        "ÇàÉ«µÀÅÛ",
                "type":        "Ñ°",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/cynrobe.c",
        ]),
        ([
                "id":          "duan qun",
                "name":        "°ÚÒÄ¶ÌÈ¹",
                "type":        "Ñ°",
                "bonus":       65,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/bduanqun.c",
        ]),
        ([
                "id":          "yao fen",
                "name":        "Ò©·Û",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/city/obj/yaofen.c",
        ]),
        ([
                "id":          "golden necklace",
                "name":        "½ðÏîÁ´",
                "type":        "Ñ°",
                "bonus":       57,
                "msg1":        "",
                "object":      "/d/city/obj/necklace.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/city/obj/cloth.c",
        ]),
        ([
                "id":          "blade",
                "name":        "¸Öµ¶",
                "type":        "Ñ°",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/city/npc/obj/gangdao.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       90,
                "msg1":        "",
                "object":      "/d/city/npc/obj/cloth.c",
        ]),
        ([
                "id":          "linen",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       60,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/linen.c",
        ]),
        ([
                "id":          "tu rou",
                "name":        "ÍÃÈâ",
                "type":        "Ñ°",
                "bonus":       80,
                "msg1":        "",
                "object":      "/d/baituo/obj/turou.c",
        ]),
        ([
                "id":          "chai dao",
                "name":        "²ñµ¶",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/baituo/obj/chaidao.c",
        ]),
        ([
                "id":          "mu chai",
                "name":        "Ä¾²ñ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/baituo/obj/chai.c",
        ]),
        ([
                "id":          "cao mei",
                "name":        "²ÝÝ®",
                "type":        "Ñ°",
                "bonus":       80,
                "msg1":        "",
                "object":      "/d/baituo/obj/caomei.c",
        ]),
});

mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
