#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "red-dress",
                "name":        "[31mÄÞºìÁ¬ÒÂÈ¹[2;37;0m",
                "type":        "Ñ°",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/red-dress.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "Çà²¼Ïâ±ßôÂôÄ",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/shaolin/obj/hui-cloth.c",
        ]),
        ([
                "id":          "panguan bi",
                "name":        "ïÙÌúÅÐ¹Ù±Ê",
                "type":        "Ñ°",
                "bonus":       81,
                "msg1":        "",
                "object":      "/d/meizhuang/npc/obj/panguan-bi.c",
        ]),
        ([
                "id":          "short blade",
                "name":        "¶Ìµ¶",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/yixing/npc/obj/shortblade.c",
        ]),
        ([
                "id":          "dilao key",
                "name":        "µØÀÎÔ¿³×",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/yaoshi.c",
        ]),
        ([
                "id":          "tiedan",
                "name":        "[1;37mÌúµ¨[2;37;0m",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/hangzhou/honghua/obj/tiedan.c",
        ]),
        ([
                "id":          "wo dao",
                "name":        "ÙÁµ¶",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/taiwan/npc/obj/wodao.c",
        ]),
        ([
                "id":          "jiujie bian",
                "name":        "¾Å½Ú±Þ",
                "type":        "Ñ°",
                "bonus":       76,
                "msg1":        "",
                "object":      "/d/yixing/npc/obj/jiujiebian.c",
        ]),
        ([
                "id":          "pi pao",
                "name":        "Ôæºì¶ÐÃæÆ¤ÅÛ",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/zaohong.c",
        ]),
        ([
                "id":          "pao",
                "name":        "°×É«µÀÅÛ",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/wudang/obj/whiterobe.c",
        ]),
        ([
                "id":          "xionghuang",
                "name":        "ÐÛ»Æ",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/shenlong/obj/xionghuang.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "»Ò²¼Ïâ±ßôÂôÄ",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/shaolin/obj/dao-cloth.c",
        ]),
        ([
                "id":          "helan huoqiang",
                "name":        "ºÉÀ¼»ðÇ¹",
                "type":        "Ñ°",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/taiwan/npc/obj/huoqiang.c",
        ]),
        ([
                "id":          "seng gun",
                "name":        "É®¹÷",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/xueshan/obj/senggun.c",
        ]),
        ([
                "id":          "shoes",
                "name":        "[32mÐå»¨Ð¬[2;37;0m",
                "type":        "Ñ°",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/shoes.c",
        ]),
        ([
                "id":          "shoes",
                "name":        "[32m²¼Ð¬[2;37;0m",
                "type":        "Ñ°",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/bu-shoes.c",
        ]),
        ([
                "id":          "hot hammer",
                "name":        "ÉÕºìµÄÌú´¸",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/village/npc/obj/hothammer.c",
        ]),
        ([
                "id":          "man dao",
                "name":        "Âùµ¶",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/mandao.c",
        ]),
        ([
                "id":          "junfu",
                "name":        "½õÒÂ¾ü·þ",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/jjunfu.c",
        ]),
        ([
                "id":          "hu pi",
                "name":        "»¢Æ¤",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/hupi.c",
        ]),
        ([
                "id":          "pink cloth",
                "name":        "·Ûºì³ñÉÀ",
                "type":        "Ñ°",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/city/obj/pink_cloth.c",
        ]),
        ([
                "id":          "blade",
                "name":        "¸Öµ¶",
                "type":        "Ñ°",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/city/obj/gangdao.c",
        ]),
        ([
                "id":          "flower shoes",
                "name":        "Ðå»¨Ð¡Ð¬",
                "type":        "Ñ°",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/city/obj/flower_shoe.c",
        ]),
        ([
                "id":          "laofang key",
                "name":        "ÀÎ·¿Ô¿³×",
                "type":        "Ñ°",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/city/npc/obj/yaoshi.c",
        ]),
        ([
                "id":          "junfu",
                "name":        "¾ü·þ",
                "type":        "Ñ°",
                "bonus":       71,
                "msg1":        "",
                "object":      "/d/city/npc/obj/junfu.c",
        ]),
        ([
                "id":          "heilong bian",
                "name":        "ºÚÁú±Þ",
                "type":        "Ñ°",
                "bonus":       71,
                "msg1":        "",
                "object":      "/d/city/npc/obj/hlbian.c",
        ]),
        ([
                "id":          "golden ring",
                "name":        "½ð½äÖ¸",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/city/npc/obj/goldring.c",
        ]),
        ([
                "id":          "jian",
                "name":        "¸Ö½£",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/city/npc/obj/gangjian.c",
        ]),
        ([
                "id":          "flower shoes",
                "name":        "Ðå»¨Ð¡Ð¬",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/city/npc/obj/flower_shoe.c",
        ]),
        ([
                "id":          "changjian",
                "name":        "³¤½£",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/city/npc/obj/changjian.c",
        ]),
        ([
                "id":          "yayi fu",
                "name":        "ÑÃÒÛ·þ",
                "type":        "Ñ°",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/yayifu.c",
        ]),
        ([
                "id":          "sword",
                "name":        "³¤½£",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/sword.c",
        ]),
        ([
                "id":          "shawei bang",
                "name":        "É±Íþ°ô",
                "type":        "Ñ°",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/shawei.c",
        ]),
        ([
                "id":          "sengyi",
                "name":        "É®ÒÂ",
                "type":        "Ñ°",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/sengyi.c",
        ]),
        ([
                "id":          "choupao",
                "name":        "³ñÅÛ",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/choupao.c",
        ]),
        ([
                "id":          "chang pao",
                "name":        "³¤ÅÛ",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/changpao.c",
        ]),
        ([
                "id":          "huang magua",
                "name":        "[1;33mÏâ±ß»ÆÂí¹Ó[2;37;0m",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/goldcloth2.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/cloth.c",
        ]),
        ([
                "id":          "duan dao",
                "name":        "¶Ìµ¶",
                "type":        "Ñ°",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/blade2.c",
        ]),
        ([
                "id":          "gang dao",
                "name":        "[1;37m¸Öµ¶[2;37;0m",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/blade1.c",
        ]),
        ([
                "id":          "si pao",
                "name":        "ÇàÉ«Ë¿ÅÛ",
                "type":        "Ñ°",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/baituo/obj/qingpao.c",
        ]),
        ([
                "id":          "da dao",
                "name":        "´óµ¶",
                "type":        "Ñ°",
                "bonus":       92,
                "msg1":        "",
                "object":      "/d/baituo/obj/dadao.c",
        ]),
});

mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
