#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "mi weiyi",
                "name":        "Ã×ÎªÒå",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/henshan/mi.c",
        ]),
        ([
                "id":          "qin juan",
                "name":        "ÇØ¾î",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hengshan/npc/qin.c",
        ]),
        ([
                "id":          "yi lin",
                "name":        "ÒÇÁÕ",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/lin.c",
        ]),
        ([
                "id":          "yi wen",
                "name":        "ÒÇÎÄ",
                "type":        "É±",
                "bonus":       97,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/wen.c",
        ]),
        ([
                "id":          "shi shuangying",
                "name":        "Ê¯Ë«Ó¢",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/shi.c",
        ]),
        ([
                "id":          "xu tianhong",
                "name":        "ÐìÌìºê",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/xu.c",
        ]),
        ([
                "id":          "wei chunhua",
                "name":        "ÎÀ´º»ª",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/wei.c",
        ]),
        ([
                "id":          "zhu cong",
                "name":        "Öì´Ï",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/guiyun/npc/zhucong.c",
        ]),
        ([
                "id":          "nan xiren",
                "name":        "ÄÏÏ£ÈÊ",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guiyun/npc/nanxiren.c",
        ]),
        ([
                "id":          "ke zhene",
                "name":        "¿ÂÕò¶ñ",
                "type":        "É±",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/guiyun/npc/kezhene.c",
        ]),
        ([
                "id":          "han baoju",
                "name":        "º«±¦¾Ô",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guiyun/npc/hanbaoju.c",
        ]),
        ([
                "id":          "xiao yuanshan",
                "name":        "ÏôÔ¶É½",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiaoyuanshan.c",
        ]),
        ([
                "id":          "yang chengxie",
                "name":        "Ñî³ÉÐ­",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/yang.c",
        ]),
        ([
                "id":          "zhang asheng",
                "name":        "ÕÅ°¢Éú",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/guiyun/npc/zhangasheng.c",
        ]),
        ([
                "id":          "han xiaoyin",
                "name":        "º«Ð¡Ó¨",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/guiyun/npc/hanxiaoying.c",
        ]),
        ([
                "id":          "danqing sheng",
                "name":        "µ¤ÇàÉú",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/meizhuang/danqing.c",
        ]),
        ([
                "id":          "zheng e",
                "name":        "Ö£Ýà",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hengshan/npc/zheng.c",
        ]),
        ([
                "id":          "li yuanzhi",
                "name":        "ÀîãäÜÆ",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/npc/liyuanzhi.c",
        ]),
        ([
                "id":          "hu qingyu",
                "name":        "ºúÇìÓà",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/npc/huqingyu.c",
        ]),
        ([
                "id":          "ye erniang",
                "name":        "Ò¶¶þÄï",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/lingzhou/npc/ye.c",
        ]),
        ([
                "id":          "xiang danian",
                "name":        "Ïò´óÄê",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/henshan/xiang.c",
        ]),
        ([
                "id":          "qu yang",
                "name":        "ÇúÑó",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/riyue/qu.c",
        ]),
        ([
                "id":          "huang boliu",
                "name":        "»Æ²®Á÷",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/heimuya/npc/huangboliu.c",
        ]),
        ([
                "id":          "quan jinfa",
                "name":        "È«½ð·¢",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/guiyun/npc/quanjinfa.c",
        ]),
        ([
                "id":          "shi lingwei",
                "name":        "Ê©ÁîÍþ",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/meizhuang/npc/shi.c",
        ]),
        ([
                "id":          "hu yuan",
                "name":        "»¤Ôº",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/meizhuang/npc/huyuan.c",
        ]),
        ([
                "id":          "nanhai eshen",
                "name":        "ÄÏº£öùÉñ",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/lingzhou/npc/nan.c",
        ]),
        ([
                "id":          "yu popo",
                "name":        "ÓàÆÅÆÅ",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/yupopo.c",
        ]),
        ([
                "id":          "ren yingying",
                "name":        "ÈÎÓ¯Ó¯",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/huashan/npc/ren-yingying.c",
        ]),
        ([
                "id":          "chen zhiyi",
                "name":        "³ÂÖ¾Òæ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/chen.c",
        ]),
        ([
                "id":          "cheng lingsu",
                "name":        "³ÌÁéËØ",
                "type":        "É±",
                "bonus":       97,
                "msg":        "",
                "object":      "/kungfu/class/hu/cheng.c",
        ]),
        ([
                "id":          "mu wanqing",
                "name":        "Ä¾ÍñÇå",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/dali/npc/muwanqing.c",
        ]),
        ([
                "id":          "xiao fei",
                "name":        "Ïô·É",
                "type":        "É±",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/xiaofei.c",
        ]),
        ([
                "id":          "ma wude",
                "name":        "ÂíÎåµÂ",
                "type":        "É±",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/mawude.c",
        ]),
        ([
                "id":          "long quan",
                "name":        "Áúîý",
                "type":        "É±",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/longquan.c",
        ]),
        ([
                "id":          "liu hongying",
                "name":        "Áõºççø",
                "type":        "É±",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/liuhongying.c",
        ]),
        ([
                "id":          "chen hu",
                "name":        "³Âä°",
                "type":        "É±",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/chenhu.c",
        ]),
        ([
                "id":          "shi qingshan",
                "name":        "Ê·ÇàÉ½",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/city/npc/shi.c",
        ]),
        ([
                "id":          "chen youde",
                "name":        "³ÂÓÐµÂ",
                "type":        "É±",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/city/npc/chen.c",
        ]),
        ([
                "id":          "xiao yuanwai",
                "name":        "ÏôÔ±Íâ",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/yuanwai.c",
        ]),
        ([
                "id":          "xiangxiang",
                "name":        "ÏæÏæ",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/xiangxiang.c",
        ]),
        ([
                "id":          "xiao qun",
                "name":        "ÏôÈº",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/tongling2.c",
        ]),
        ([
                "id":          "zhang heng",
                "name":        "ÕÅºâ",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/tongling1.c",
        ]),
        ([
                "id":          "huitong chanshi",
                "name":        "»ÛÍ¨ìøÊ¦",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/huitong.c",
        ]),
        ([
                "id":          "dubi shenni",
                "name":        "¶À±ÛÉñÄá",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/beijing/npc/dubi.c",
        ]),
        ([
                "id":          "ma chaoxing",
                "name":        "Âí³¬ÐË",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/yunlong/ma.c",
        ]),
        ([
                "id":          "kang guangling",
                "name":        "¿µ¹ãÁê",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/kanggl.c",
        ]),
        ([
                "id":          "song qingshu",
                "name":        "ËÎÇàÊé",
                "type":        "É±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/wudang/xiaosong.c",
        ]),
        ([
                "id":          "huang rong",
                "name":        "»ÆÈØ",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/taohua/rong.c",
        ]),
        ([
                "id":          "yin zhiping",
                "name":        "ÒüÖ¾Æ½",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/yin.c",
        ]),
        ([
                "id":          "zuo quan",
                "name":        "×óÈ«",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/zuo-qu.c",
        ]),
        ([
                "id":          "ma juwei",
                "name":        "Âí¾ãÎª",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/ma-jw.c",
        ]),
        ([
                "id":          "li futou",
                "name":        "Àî¸«Í·",
                "type":        "É±",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/li-futou.c",
        ]),
        ([
                "id":          "he bujing",
                "name":        "ºÎ²»¾»",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/he-bj.c",
        ]),
        ([
                "id":          "jingkong shitai",
                "name":        "¾²¿ÕÊ¦Ì«",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/emei/kong.c",
        ]),
        ([
                "id":          "jingjia shitai",
                "name":        "¾²åÈÊ¦Ì«",
                "type":        "É±",
                "bonus":       92,
                "msg":        "",
                "object":      "/kungfu/class/emei/jia.c",
        ]),
        ([
                "id":          "ji xiaofu",
                "name":        "¼ÍÏþÜ½",
                "type":        "É±",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/emei/ji.c",
        ]),
        ([
                "id":          "jinghui shitai",
                "name":        "¾²»ÛÊ¦Ì«",
                "type":        "É±",
                "bonus":       93,
                "msg":        "",
                "object":      "/kungfu/class/emei/hui.c",
        ]),
        ([
                "id":          "jinghe shitai",
                "name":        "¾²ºÍÊ¦Ì«",
                "type":        "É±",
                "bonus":       62,
                "msg":        "",
                "object":      "/kungfu/class/emei/he.c",
        ]),
        ([
                "id":          "jingfeng shitai",
                "name":        "¾²·çÊ¦Ì«",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/emei/feng.c",
        ]),
        ([
                "id":          "jingdao shitai",
                "name":        "¾²µÀÊ¦Ì«",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/dao.c",
        ]),
        ([
                "id":          "bei jinyi",
                "name":        "±´½õÒÇ",
                "type":        "É±",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/emei/bei.c",
        ]),
        ([
                "id":          "zhu wanli",
                "name":        "ñÒÍòÀï",
                "type":        "É±",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/dali/chuwanli.c",
        ]),
        ([
                "id":          "zhu danchen",
                "name":        "Öìµ¤³¼",
                "type":        "É±",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/dali/zhudanchen.c",
        ]),
        ([
                "id":          "gu ducheng",
                "name":        "¹ÅóÆ³Ï",
                "type":        "É±",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/dali/guducheng.c",
        ]),
        ([
                "id":          "fu sigui",
                "name":        "¸µË¼¹é",
                "type":        "É±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/dali/fusigui.c",
        ]),
        ([
                "id":          "chu wanli",
                "name":        "ñÒÍòÀï",
                "type":        "É±",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/dali/chuwanli.c",
        ]),
});
mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
