#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "yaochu",
                "name":        "Ò©³ú",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/xingxiu/obj/yaochu.c",
        ]),
        ([
                "id":          "piqiu",
                "name":        "Æ¤ôÃ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/guanwai/npc/obj/piqiu.c",
        ]),
        ([
                "id":          "card3",
                "name":        "ÇàÁúÌÃÁîÅÆ",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/card3.c",
        ]),
        ([
                "id":          "cai dao",
                "name":        "²Ëµ¶",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/foshan/npc/obj/caidao.c",
        ]),
        ([
                "id":          "pink cloth",
                "name":        "·Ûºì³ñÉÀ",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/pink_cloth.c",
        ]),
        ([
                "id":          "jin duan",
                "name":        "½õ¶Ð",
                "type":        "Ñ°",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/quanzhen/npc/obj/jinduan.c",
        ]),
        ([
                "id":          "blade",
                "name":        "¸Öµ¶",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/quanzhen/npc/obj/gangdao.c",
        ]),
        ([
                "id":          "mu tang",
                "name":        "Ä¾ïÛ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/mingjiao/obj/mutang.c",
        ]),
        ([
                "id":          "tie qiao",
                "name":        "ÌúÇÂ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/tieqiao.c",
        ]),
        ([
                "id":          "fenshui ci",
                "name":        "·ÖË®´Ì",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/fenshuici.c",
        ]),
        ([
                "id":          "golden necklace",
                "name":        "½ðÏîÁ´",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/necklace.c",
        ]),
        ([
                "id":          "junfu",
                "name":        "¾ü·þ",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/quanzhen/npc/obj/junfu.c",
        ]),
        ([
                "id":          "Shui kao",
                "name":        "Ò¹ÐÐË®¿¿",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/shuikao.c",
        ]),
        ([
                "id":          "futou",
                "name":        "´ó¸«Í·",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/futou.c",
        ]),
        ([
                "id":          "sangmen fu",
                "name":        "É¥ÃÅ¸«",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/axe.c",
        ]),
        ([
                "id":          "golden ring",
                "name":        "½ð½äÖ¸",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/goldring.c",
        ]),
        ([
                "id":          "blade",
                "name":        "¸Öµ¶",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/xiaoyao/npc/obj/blade.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "»Æ²¼ôÂôÄ",
                "type":        "Ñ°",
                "bonus":       70,
                "msg1":        "",
                "object":      "/d/shaolin/obj/xu-cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "Çà²¼É®ÒÂ",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/shaolin/obj/cloth.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "½ð±ßºÚ²¼ôÂôÄ",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/shaolin/obj/cheng-cloth.c",
        ]),
        ([
                "id":          "changjian",
                "name":        "³¤½£",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/changjian.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/xiaoyao/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "[1;36mÇ³À¶É«Âí¹Ó[2;37;0m",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/cloth.c",
        ]),
        ([
                "id":          "yayi cloth",
                "name":        "ÑÃÒÛ·þ",
                "type":        "Ñ°",
                "bonus":       53,
                "msg1":        "",
                "object":      "/d/suzhou/npc/obj/yayifu.c",
        ]),
        ([
                "id":          "green cloth",
                "name":        "´äÂÌ³ñÉÀ",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/green_cloth.c",
        ]),
        ([
                "id":          "flower shoes",
                "name":        "Ðå»¨Ð¡Ð¬",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/yanziwu/npc/obj/flower_shoe.c",
        ]),
        ([
                "id":          "mini-ao",
                "name":        "[34m²Ê¶Ð½ôÉí°À[2;37;0m",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/mini-dress.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "°×²¼ºÚ±ßôÂôÄ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/shaolin/obj/qing-cloth.c",
        ]),
        ([
                "id":          "xiao ao",
                "name":        "Ô²ÁìÐ¡°À",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/xiaoao.c",
        ]),
        ([
                "id":          "bai yi",
                "name":        "°×ÒÂ",
                "type":        "Ñ°",
                "bonus":       51,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/whitecloth.c",
        ]),
        ([
                "id":          "chang qun",
                "name":        "ÎÚÒÄ³¤È¹",
                "type":        "Ñ°",
                "bonus":       51,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/wchangqun.c",
        ]),
        ([
                "id":          "tou jin",
                "name":        "Ì¨ÒÄÍ·½í",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/ttoujin.c",
        ]),
        ([
                "id":          "junfu",
                "name":        "»ÆÒÂ¾ü·þ",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/junfu.c",
        ]),
        ([
                "id":          "junfu",
                "name":        "¾ü·þ",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/city/obj/junfu.c",
        ]),
        ([
                "id":          "jitui",
                "name":        "¿¾¼¦ÍÈ",
                "type":        "Ñ°",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/city/obj/jitui.c",
        ]),
        ([
                "id":          "changjian",
                "name":        "³¤½£",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/city/obj/changjian.c",
        ]),
        ([
                "id":          "yayi cloth",
                "name":        "ÑÃÒÛ·þ",
                "type":        "Ñ°",
                "bonus":       53,
                "msg1":        "",
                "object":      "/d/city/npc/obj/yayifu.c",
        ]),
        ([
                "id":          "pink cloth",
                "name":        "·Ûºì³ñÉÀ",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/city/npc/obj/pink_cloth.c",
        ]),
        ([
                "id":          "golden necklace",
                "name":        "½ðÏîÁ´",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/city/npc/obj/necklace.c",
        ]),
        ([
                "id":          "blade",
                "name":        "¸Öµ¶",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/city/npc/obj/gangdao.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/city/npc/obj/cloth.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "±ø·þ",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/bingfu.c",
        ]),
        ([
                "id":          "key",
                "name":        "Ô¿³×",
                "type":        "Ñ°",
                "bonus":       82,
                "msg1":        "",
                "object":      "/d/baituo/obj/key.c",
        ]),
});

mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
