#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "Yelv qi",
                "name":        "“Æ¬…∆Î",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/yelvqi.c",
        ]),
        ([
                "id":          "chi baicheng",
                "name":        "≥Ÿ∞Ÿ≥«",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taishan/npc/chi.c",
        ]),
        ([
                "id":          "huangzhong gong",
                "name":        "ª∆÷”π´",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/meizhuang/huang.c",
        ]),
        ([
                "id":          "ju jian",
                "name":        "æ’Ω£",
                "type":        "…±",
                "bonus":       66,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/jujian.c",
        ]),
        ([
                "id":          "yi he",
                "name":        "“«∫Õ",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/he.c",
        ]),
        ([
                "id":          "ren ying ying",
                "name":        "»Œ”Ø”Ø",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/heimuya/npc/obj/ren.c",
        ]),
        ([
                "id":          "gongye qian",
                "name":        "π´“±«¨",
                "type":        "…±",
                "bonus":       82,
                "msg":        "",
                "object":      "/d/yanziwu/npc/gongye.c",
        ]),
        ([
                "id":          "lan jian",
                "name":        "¿ºΩ£",
                "type":        "…±",
                "bonus":       62,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/lanjian.c",
        ]),
        ([
                "id":          "tianmen daoren",
                "name":        "ÃÏ√≈µ¿»À",
                "type":        "…±",
                "bonus":       100,
                "msg":        "",
                "object":      "/kungfu/class/taishan/tianmen.c",
        ]),
        ([
                "id":          "lu lianrong",
                "name":        "¬≥¡¨»Ÿ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/henshan/lu.c",
        ]),
        ([
                "id":          "ren yingying",
                "name":        "»Œ”Ø”Ø",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/heimuya/npc/ren.c",
        ]),
        ([
                "id":          "fu mingyi",
                "name":        "∑˚√Ù“«",
                "type":        "…±",
                "bonus":       62,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/fumingyi.c",
        ]),
        ([
                "id":          "feng boe",
                "name":        "∑Á≤®∂Ò",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/yanziwu/npc/feng.c",
        ]),
        ([
                "id":          "huang zhen",
                "name":        "ª∆’Ê",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/xiangyang/npc/huangzhen.c",
        ]),
        ([
                "id":          "yi zhi",
                "name":        "“«÷ ",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/zhi.c",
        ]),
        ([
                "id":          "ren ying ying",
                "name":        "»Œ”Ø”Ø",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/heimuya/npc/ren1.c",
        ]),
        ([
                "id":          "zhao banshan",
                "name":        "’‘∞Î…Ω",
                "type":        "…±",
                "bonus":       100,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/zhao.c",
        ]),
        ([
                "id":          "chang bozhi",
                "name":        "≥£≤Æ÷æ",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/chang2.c",
        ]),
        ([
                "id":          "chang hezhi",
                "name":        "≥£∫’÷æ",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/chang1.c",
        ]),
        ([
                "id":          "yi qing",
                "name":        "“««Â",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/qing.c",
        ]),
        ([
                "id":          "deng baichuan",
                "name":        "µÀ∞Ÿ¥®",
                "type":        "…±",
                "bonus":       95,
                "msg":        "",
                "object":      "/d/yanziwu/npc/deng.c",
        ]),
        ([
                "id":          "huiyue shi",
                "name":        "ª‘‘¬ π",
                "type":        "…±",
                "bonus":       100,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/huiyue.c",
        ]),
        ([
                "id":          "zhu jian",
                "name":        "÷ÒΩ£",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/zhujian.c",
        ]),
        ([
                "id":          "wen tailai",
                "name":        "ŒƒÃ©¿¥",
                "type":        "…±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/wen.c",
        ]),
        ([
                "id":          "huo qingtong",
                "name":        "ªÙ«‡Õ©",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/huo.c",
        ]),
        ([
                "id":          "bao butong",
                "name":        "∞¸≤ªÕ¨",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/yanziwu/npc/bao.c",
        ]),
        ([
                "id":          "mu wanqing",
                "name":        "ƒæÕÒ«Â",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/mu.c",
        ]),
        ([
                "id":          "miaofeng shi",
                "name":        "√Ó∑Á π",
                "type":        "…±",
                "bonus":       100,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/miaofeng.c",
        ]),
        ([
                "id":          "nv lang",
                "name":        "√…√Ê≈Æ¿…",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/lingjiu/npc/nvlang.c",
        ]),
        ([
                "id":          "sun buer",
                "name":        "ÀÔ≤ª∂˛",
                "type":        "…±",
                "bonus":       86,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/sun.c",
        ]),
        ([
                "id":          "hao datong",
                "name":        "∫¬¥ÛÕ®",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/hao.c",
        ]),
        ([
                "id":          "mei jian",
                "name":        "√∑Ω£",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/meijian.c",
        ]),
        ([
                "id":          "yue wife",
                "name":        "‘¿∑Ú»À",
                "type":        "…±",
                "bonus":       92,
                "msg":        "",
                "object":      "/kungfu/class/huashan/yue-wife.c",
        ]),
/*
        ([
                "id":          "guxu daozhang",
                "name":        "π»–Èµ¿≥§",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/wudang/guxu.c",
        ]),
*/
        ([
                "id":          "yu hongxing",
                "name":        "”‡∫È–À",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/yu-hx.c",
        ]),
        ([
                "id":          "quan guanqing",
                "name":        "»´π⁄«Â",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/quan-gq.c",
        ]),
        ([
                "id":          "li sheng",
                "name":        "¿Ë…˙",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/li-sh.c",
        ]),
        ([
                "id":          "jingxuan shitai",
                "name":        "æ≤–˛ ¶Ã´",
                "type":        "…±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/emei/xuan.c",
        ]),
        ([
                "id":          "jingxu shitai",
                "name":        "æ≤–È ¶Ã´",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/emei/xu.c",
        ]),
        ([
                "id":          "dao baifeng",
                "name":        "µ∂∞◊∑Ô",
                "type":        "…±",
                "bonus":       62,
                "msg":        "",
                "object":      "/kungfu/class/duan/daobf.c",
        ]),
        ([
                "id":          "hua hegen",
                "name":        "ª™∫’Ùﬁ",
                "type":        "…±",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/dali/huahegen.c",
        ]),
        ([
                "id":          "gao shengtai",
                "name":        "∏ﬂ…˝Ã©",
                "type":        "…±",
                "bonus":       92,
                "msg":        "",
                "object":      "/kungfu/class/dali/gaoshengtai.c",
        ]),
        ([
                "id":          "fan ye",
                "name":        "∑∂ÊË",
                "type":        "…±",
                "bonus":       66,
                "msg":        "",
                "object":      "/kungfu/class/dali/fanye.c",
        ]),
        ([
                "id":          "ba tianshi",
                "name":        "∞ÕÃÏ Ø",
                "type":        "…±",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/dali/batianshi.c",
        ]),
});
mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
