#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "liuyun shi",
                "name":        "¡˜‘∆ π",
                "type":        "…±",
                "bonus":       89,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/liuyun.c",
        ]),
        ([
                "id":          "shanzei tou",
                "name":        "…Ω‘ÙÕ∑",
                "type":        "…±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/baituo/npc/shanzei3.c",
        ]),
        ([
                "id":          "yu zu",
                "name":        "”¸◊‰",
                "type":        "…±",
                "bonus":       110,
                "msg":        "",
                "object":      "/d/shaolin/npc/yu-zu.c",
        ]),
        ([
                "id":          "lin pingzhi",
                "name":        "¡÷∆Ω÷Æ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/lin-pingzhi.c",
        ]),
        ([
                "id":          "liu zhengfeng",
                "name":        "¡ı’˝∑Á",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/henshan/liu.c",
        ]),
        ([
                "id":          "dingyi shitai",
                "name":        "∂®“› ¶Ã´",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/yi.c",
        ]),
        ([
                "id":          "dingxian shitai",
                "name":        "∂®œ– ¶Ã´",
                "type":        "…±",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/xian.c",
        ]),
        ([
                "id":          "tianmen daoren",
                "name":        "ÃÏ√≈µ¿»À",
                "type":        "…±",
                "bonus":       66,
                "msg":        "",
                "object":      "/kungfu/class/taishan/tianmen.c",
        ]),
        ([
                "id":          "dingjing shitai",
                "name":        "∂®æ≤ ¶Ã´",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/jing.c",
        ]),
        ([
                "id":          "tubi weng",
                "name":        "Õ∫± ŒÃ",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/meizhuang/tubi.c",
        ]),
        ([
                "id":          "zhao banshan",
                "name":        "’‘∞Î…Ω",
                "type":        "…±",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/zhao.c",
        ]),
        ([
                "id":          "yu yutong",
                "name":        "”‡”„Õ¨",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/yu.c",
        ]),
        ([
                "id":          "wuchen daozhang",
                "name":        "Œﬁ≥æµ¿≥§",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/wuchen.c",
        ]),
        ([
                "id":          "lu feiqing",
                "name":        "¬Ω∑∆«‡",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/lu.c",
        ]),
        ([
                "id":          "huangmei dashi",
                "name":        "ª∆√º¥Û ¶",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/monk.c",
        ]),
        ([
                "id":          "zhou botong",
                "name":        "÷‹≤ÆÕ®",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/taohua/npc/zhou.c",
        ]),
        ([
                "id":          "zhou zhongying",
                "name":        "÷‹÷Ÿ”¢",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/zhou.c",
        ]),
        ([
                "id":          "huiyue shi",
                "name":        "ª‘‘¬ π",
                "type":        "…±",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/huiyue.c",
        ]),
        ([
                "id":          "mo da",
                "name":        "ƒ™¥Û",
                "type":        "…±",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/henshan/mo.c",
        ]),
        ([
                "id":          "dabei laoren",
                "name":        "¥Û±Ø¿œ»À",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/yixing/npc/dabei.c",
        ]),
        ([
                "id":          "yuan ziyi",
                "name":        "‘¨◊œ“¬",
                "type":        "…±",
                "bonus":       106,
                "msg":        "",
                "object":      "/d/henshan/npc/yuanziyi.c",
        ]),
        ([
                "id":          "miaofeng shi",
                "name":        "√Ó∑Á π",
                "type":        "…±",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/miaofeng.c",
        ]),
        ([
                "id":          "qiu chuji",
                "name":        "«¥¶ª˙",
                "type":        "…±",
                "bonus":       100,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/qiu.c",
        ]),
        ([
                "id":          "liu chuxuan",
                "name":        "¡ı¥¶–˛",
                "type":        "…±",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/liu.c",
        ]),
        ([
                "id":          "yin tianzheng",
                "name":        "“ÛÃÏ’˝",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/yintianzheng.c",
        ]),
        ([
                "id":          "yang xiao",
                "name":        "—ÓÂ–",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/yangxiao.c",
        ]),
        ([
                "id":          "xie xun",
                "name":        "–ª—∑",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/xiexun.c",
        ]),
        ([
                "id":          "fan yao",
                "name":        "∑∂“£",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/fanyao.c",
        ]),
        ([
                "id":          "huangmei dashi",
                "name":        "ª∆√º¥Û ¶",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/dali/npc/huangmei.c",
        ]),
        ([
                "id":          "taoshi xian",
                "name":        "Ã“ µœ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao6.c",
        ]),
        ([
                "id":          "taohua xian",
                "name":        "Ã“ª®œ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao5.c",
        ]),
        ([
                "id":          "taoye xian",
                "name":        "Ã““∂œ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao4.c",
        ]),
        ([
                "id":          "taozhi xian",
                "name":        "Ã“÷¶œ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao3.c",
        ]),
        ([
                "id":          "taogan xian",
                "name":        "Ã“∏…œ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao2.c",
        ]),
        ([
                "id":          "taogen xian",
                "name":        "Ã“∏˘œ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao1.c",
        ]),
        ([
                "id":          "duo long",
                "name":        "∂‡¬°",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/beijing/npc/duolong.c",
        ]),
        ([
                "id":          "yin litin",
                "name":        "“Û¿ÊÕ§",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/wudang/yin.c",
        ]),
        ([
                "id":          "zhang songxi",
                "name":        "’≈À…œ™",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/wudang/xi.c",
        ]),
        ([
                "id":          "song yuanqiao",
                "name":        "ÀŒ‘∂«≈",
                "type":        "…±",
                "bonus":       106,
                "msg":        "",
                "object":      "/kungfu/class/wudang/song.c",
        ]),
        ([
                "id":          "zhang cuishan",
                "name":        "’≈¥‰…Ω",
                "type":        "…±",
                "bonus":       100,
                "msg":        "",
                "object":      "/kungfu/class/wudang/shan.c",
        ]),
        ([
                "id":          "mo shenggu",
                "name":        "ƒ™…˘π»",
                "type":        "…±",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/wudang/mo.c",
        ]),
        ([
                "id":          "ben yin",
                "name":        "±æ“Ú",
                "type":        "…±",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/tianlongsi/benyin.c",
        ]),
        ([
                "id":          "ben xiang",
                "name":        "±æœ‡",
                "type":        "…±",
                "bonus":       100,
                "msg":        "",
                "object":      "/kungfu/class/tianlongsi/benxiang.c",
        ]),
        ([
                "id":          "ben guan",
                "name":        "±æπ€",
                "type":        "…±",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/tianlongsi/benguan.c",
        ]),
        ([
                "id":          "wen cangsong",
                "name":        "Œ≈≤‘À…",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/wensong.c",
        ]),
        ([
                "id":          "ben can",
                "name":        "±æ≤Œ",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/tianlongsi/bencan.c",
        ]),
        ([
                "id":          "qu lingfeng",
                "name":        "«˙»˝",
                "type":        "…±",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/taohua/qu.c",
        ]),
        ([
                "id":          "lu chengfeng",
                "name":        "¬Ω≥À∑Á",
                "type":        "…±",
                "bonus":       106,
                "msg":        "",
                "object":      "/kungfu/class/taohua/lu.c",
        ]),
        ([
                "id":          "feng mofeng",
                "name":        "∑ÎÃ˙Ω≥",
                "type":        "…±",
                "bonus":       74,
                "msg":        "",
                "object":      "/kungfu/class/taohua/feng.c",
        ]),
        ([
                "id":          "xuannan dashi",
                "name":        "–˛ƒ—¥Û ¶",
                "type":        "…±",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xuan-nan.c",
        ]),
        ([
                "id":          "xuanku dashi",
                "name":        "–˛ø‡¥Û ¶",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xuan-ku.c",
        ]),
        ([
                "id":          "wang chuyi",
                "name":        "Õı¥¶“ª",
                "type":        "…±",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/wangchuyi.c",
        ]),
        ([
                "id":          "tan chuduan",
                "name":        "Ã∑¥¶∂À",
                "type":        "…±",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/tan.c",
        ]),
        ([
                "id":          "xi zhanglao",
                "name":        "ﬁ…≥§¿œ",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/xi.c",
        ]),
        ([
                "id":          "lu youjiao",
                "name":        "¬≥”–Ω≈",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/lu.c",
        ]),
        ([
                "id":          "liang zhanglao",
                "name":        "¡∫≥§¿œ",
                "type":        "…±",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/liang.c",
        ]),
        ([
                "id":          "jian zhanglao",
                "name":        "ºÚ≥§¿œ",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/jian.c",
        ]),
        ([
                "id":          "zhou zhiruo",
                "name":        "÷‹‹∆»Ù",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/emei/zhou.c",
        ]),
        ([
                "id":          "duan yu",
                "name":        "∂Œ”˛",
                "type":        "…±",
                "bonus":       106,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyu.c",
        ]),
        ([
                "id":          "miao renfeng",
                "name":        "√Á»À∑Ô",
                "type":        "…±",
                "bonus":       82,
                "msg":        "",
                "object":      "/d/shaolin/npc/miao.c",
        ]),
        ([
                "id":          "chen jialuo",
                "name":        "≥¬º“¬Â",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/chen.c",
        ]),
        ([
                "id":          "yue nv",
                "name":        "‘Ω≈Æ",
                "type":        "…±",
                "bonus":       85,
                "msg":        "",
                "object":      "/d/hangzhou/npc/yuenv.c",
        ]),
        ([
                "id":          "yuan ziyi",
                "name":        "‘¨◊œ“¬",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/henshan/npc/yuanziyi.c",
        ]),
        ([
                "id":          "murong longcheng",
                "name":        "ƒΩ»›¡˙≥«",
                "type":        "…±",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/murong/longcheng.c",
        ]),
        ([
                "id":          "wei yixiao",
                "name":        "Œ§“ª–¶",
                "type":        "…±",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/weiyixiao.c",
        ]),
        ([
                "id":          "zhuo bufan",
                "name":        "◊ø≤ª∑≤",
                "type":        "…±",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/zhuo.c",
        ]),
        ([
                "id":          "linghu chong",
                "name":        "¡Ó∫¸≥Â",
                "type":        "…±",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/huashan/linghu.c",
        ]),
        ([
                "id":          "gao laozhe",
                "name":        "∏ﬂ¿œ’ﬂ",
                "type":        "…±",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/huashan/gao-laozhe.c",
        ]),
        ([
                "id":          "feng qingyang",
                "name":        "∑Á«Â—Ô",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/huashan/feng.c",
        ]),
        ([
                "id":          "ai laozhe",
                "name":        "∞´¿œ’ﬂ",
                "type":        "…±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/huashan/ai-laozhe.c",
        ]),
        ([
                "id":          "hu yizhi",
                "name":        "∫˙“›÷Æ",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/hu/huyizhi.c",
        ]),
        ([
                "id":          "yang guo",
                "name":        "—Óπ˝",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/gumu/yang.c",
        ]),
        ([
                "id":          "chen jinnan",
                "name":        "≥¬Ω¸ƒœ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/yunlong/chen.c",
        ]),
        ([
                "id":          "song yuanqiao",
                "name":        "ÀŒ‘∂«≈",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/wudang/song.c",
        ]),
        ([
                "id":          "kurong",
                "name":        "ø›»Ÿ¥Û ¶",
                "type":        "…±",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/tianlongsi/kurong.c",
        ]),
        ([
                "id":          "lu chengfeng",
                "name":        "¬Ω≥À∑Á",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/taohua/lu.c",
        ]),
        ([
                "id":          "xuanbei dashi",
                "name":        "–˛±Ø¥Û ¶",
                "type":        "…±",
                "bonus":       76,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xuan-bei.c",
        ]),
        ([
                "id":          "wuming laoseng",
                "name":        "Œﬁ√˚¿œ…Æ",
                "type":        "…±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/wuming.c",
        ]),
        ([
                "id":          "kong jian",
                "name":        "ø’º˚",
                "type":        "…±",
                "bonus":       85,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/kong-jian.c",
        ]),
        ([
                "id":          "du nan",
                "name":        "∂…ƒ—",
                "type":        "…±",
                "bonus":       85,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-nan.c",
        ]),
        ([
                "id":          "du jie",
                "name":        "∂…ΩŸ",
                "type":        "…±",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-jie.c",
        ]),
        ([
                "id":          "du e",
                "name":        "∂…∂Ú",
                "type":        "…±",
                "bonus":       84,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-e.c",
        ]),
        ([
                "id":          "zhou botong",
                "name":        "÷‹≤ÆÕ®",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/zhou.c",
        ]),
        ([
                "id":          "wang chongyang",
                "name":        "Õı÷ÿ—Ù",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/wang.c",
        ]),
        ([
                "id":          "lin chaoying",
                "name":        "¡÷≥Ø”¢",
                "type":        "…±",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/gumu/lin.c",
        ]),
        ([
                "id":          "ma dayuan",
                "name":        "¬Ì¥Û‘™",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/ma.c",
        ]),
        ([
                "id":          "yideng dashi",
                "name":        "“ªµ∆¥Û ¶",
                "type":        "…±",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/duan/yideng.c",
        ]),
        ([
                "id":          "duan zhengming",
                "name":        "∂Œ’˝√˜",
                "type":        "…±",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanzm.c",
        ]),
        ([
                "id":          "duan yu",
                "name":        "∂Œ”˛",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyu.c",
        ]),
        ([
                "id":          "duan yanqing",
                "name":        "∂Œ—”«Ï",
                "type":        "…±",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyq.c",
        ]),
});
mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
