// Code of ShenZhou
mapping *drug_list = ({
        ([
                "name": "ÑøÐÄÍè",
                "file": "yangxin",
                "time": 5,
                "s": 15,
                "d": 5,
                "n": 0,
        ]),
        ([
                "name": "¹éÔªµ¤",
                "file": "guiyuan",
                "time": 5,
                "s": 15,
                "d": 5,
                "n": 0,
        ]),
        ([
                "name": "½ð´´Ò©",
                "file": "jinchuang",
                "time": 10,
                "s": 20,
                "d": 0,
                            "n": 15,
        ]),
        ([
                "name": "°Ù²Ýµ¤",
                "file": "baicao-dan",
                "time": 15,
                "s": 30,
                "d": 0,
                "n": 30,
        ]),
        ([
                "name": "¾Å»¨ÓñÂ¶Íè",
                "file": "yulu-wan",
                "time": 30,
                "s": 50,
                "d": 39,
                "n": 40,
        ]),
        ([
                "name": "ÌïÆßöèµ¨É¢",
                "file": "tianqi-san",
                "time": 45,
                "s": 5,
                                "d": 85,
                "n": 10,
        ]),
        ([
                "name": "ÇåÐÄÉ¢",
                "file": "xxqingxin-san",
                "time": 15,
                "s": -1,
                "d": 20,
                "n": 0,
        ]),
        ([
                "name": "Ñø¾«µ¤",
                "file": "yangjing",
                "time": 5,
                "s": 0,
                "d": 8,
                "n": 0,
        ]),
        ([
                "name": "ÉßÒ©",
                "file": "sheyao",
                "time": 10,
                         "s": 0,
                "d": 40,
                "n": 0,
        ]),
        ([
                "name": "ÐøÃü°Ëµ¤",
                "file": "badan",
                "time": 60,
                "s": 125,
                "d": 55,
                "n": 63,
        ]),
        ([
                "name": "Í¨Ï¬µØÁúÍè",
                "file": "dilong-wan",
                "time": 100,
                "s": 20,
                "d": 142,
                "n": 80,
        ]),
        ([
                "name": "Óñ¶´ºÚÊ¯µ¤",
                "file": "heishi-dan",
                         "time": 80,
                "s": 80,
                "d": 30,
                "n": 167,
        ]),
        ([
                "name": "»ØÑôÎåÁúÉ¢",
                "file": "huiyang-san",
                "time": 30,
                "s": 40,
                "d": 10,
                "n": 88,
        ]),
        ([
                "name": "ÁéÐÄµ¤",
                "file": "lingxin-dan",
                "time": 10,
                "s": 110,
                "d": 30,
                "n": 87,
        ]),
        ([
                "name": "Èý»Æ±¦À¯Íè",
                        "file": "sanhuang-wan",
                "time": 50,
                "s": 5,
                "d": 90,
                "n": 0,
        ]),
        ([
                "name": "ÈË²ÎÑøÈÙÍè",
                "file": "yangrong-wan",
                "time": 40,
                "s": 185,
                "d": 30,
                "n": 10,
        ]),
        ([
                "name": "ÓñÕæÉ¢",
                "file": "yuzhen-san",
                "time": 30,
                "s": 43,
                "d": 30,
                "n": 0,
        ]),
        ([
        "name": "×íÏÉÃÛ",
                "file": "zuixian-mi",
                "time": 10,
                "s": 39,
                "d": 2,
                "n": 30,
        ]),
        ([
                "name": "´óÁ¦Íè",
                "file": "dali-wan",
                "time": 50,
                "s": 90,
                "d": 0,
                "n": 147,
        ]),
                ([
                                "name": "²¹ÒõÍè",
                "file": "buyin-wan",
                "time": 60,
                "s": 0,
                "d": -200,
                "n": 200,
        ])

});