#include <ansi.h>

mapping all_type = ([
        "weapon" : ({ "blade", "club", "hammer", "sword", "staff", "whip", "throwing", "xsword", }),
        "armor"  : ({ "armor", "boots", "cloth", "hands", "finger", "head", "waist", "wrists", "surcoat", }),
        "rings"  : ({ "rings", "neck", "charm", }),
        "gem"    : ({ "gem", }),
]);

string *weapon_type = ({
        "blade", "hammer", "sword", "staff", "whip", "club", "throwing", "xsword",
}); 

string *armor_type = ({
        "armor", "boots", "cloth", "hands", "finger", "head", "waist", "wrists", "surcoat",
});

string *rings_type = ({
        "rings", "neck", "charm",
});

string *item_color = ({
          HIW,         HIB,         HIC,         HIR,         HIM,         HIY,         HIG,
          WHT,         BLU,         CYN,         RED,         MAG,         YEL,         NOR,
});

mapping type_list = ([
        "blade"                :        
                ([
                        "½ğ±³´ó¿³µ¶"        :        "jinbei blade", 
                        "ÃÅÉÈ´óµ¶"        :        "menshan blade", 
                        "Æë·ï³¯Ñôµ¶"        :        "chaoyang blade",  
                        "Ïó±Ç¹ÅÔÂµ¶"        :        "guyue blade",  
                        "¿³É½µ¶"        :        "kanshan blade",  
                        "Èı¼âÁ½ÈĞµ¶"        :        "sanjian blade",  
                        "ºÏÉÈ°åÃÅµ¶"        :        "heshan blade", 
                        "½ğ±³¿³É½µ¶"        :        "kanshan blade",  
                        "Ñãôáµ¶"        :        "yanling blade",  
                        "ÇàÍ­µ¶"        :        "qingtong blade",  
                        "µ¤·ïµ¶"        :        "danfeng blade",  
                        "°åÃÅºìÓ§µ¶"        :        "hongying blade",  
                        "ĞâÈŞµ¶"        :        "xiurong blade",  
                        "ÆßĞÇß¡»¨µ¶"        :        "qixing blade",  
                        "»¢ÑÀµ¶"        :        "huya blade", 
                        "¾Å¶ú°Ë»·µ¶"        :        "bahuan blade",  
                        "ÓãÁÛ×Ï½ğµ¶"        :        "yulin blade",  
                        "Èı²æ¹íÍ·µ¶"        :        "guitou blade",  
                        "ÁÁÒøµ¶"        :        "liangyin blade",  
                        "µç¹âµ¶"        :        "dianguang blade",  
                        "Æß±¦´ë½ğµ¶"        :        "cuojin blade",  
                        "³àÍ­µ¶"        :        "chitong blade",  
                        "ÅüË®µ¶"        :        "pishui blade",  
                        "Çà¸Öµ¶"        :        "qinggang blade", 
                ]),

        "hammer"        :        
                ([
                        "°ËÀã×Ï½ğ´¸"        :        "zijin hammer",   
                        "°ËÀã»Æ½ğ´¸"        :        "huangjin hammer",    
                        "°ËØÔÉúÍ­´¸"        :        "shengtong hammer",    
                        "°ËÀãÁÁÒø´¸"        :        "liangyin hammer",    
                        "ïÙÌúÔşÓÍ´¸"        :        "bingtie hammer",    
                        "°ËØÔÁÁÒø´¸"        :        "bagua hammer",    
                        "ÀŞ¹ÄÎÍ½ğ´¸"        :        "leigu hammer",    
                        "ÁúÍ·Á´×Ó´¸"        :        "longtou hammer",   
                        "°ËÀãÉúÌú´¸"        :        "baleng hammer",    
                        "°ËØÔïÙÌú´¸"        :        "bagua hammer",    
                        "ºÚ»¢Í­´¸"        :        "heihu hammer",    
                        "ÎÚ½ğ´¸"        :        "wujin hammer",    
                        "Ñ¹°ÑÀÁÁú´¸"        :        "lanlong hammer",    
                        "ÈËÃæ³àÍ­´¸"        :        "chitong hammer",    
                        "¹ÏËó´¸"        :        "guasuo hammer",    
                        "°Ë±¦µç¹â´¸"        :        "dianguang hammer",    
                        "ÇàÍ­Á´×Ó´¸"        :        "lianzi hammer",    
                        "µç¹â×Ï½ğ´¸"        :        "zijin hammer",    
                        "°ËÀâÍ­´¸"        :        "baleng hammer",    
                        "»ëÔ²´¸"        :        "hunyuan hammer",    
                        "ÇàÍ­ÎÑ¹Ï´¸"        :        "wogua hammer",   
                        "×ÓÄ¸Ô§Ñì´¸"        :        "zimu hammer",    
                        "ÁÁÒøÁ´×Ó´¸"        :        "lianzi hammer",    
                        "°Ë½Ç×Ï½ğ´¸"        :        "bajiao hammer",    
                        "ºìÍ­´¸"        :        "hongtong hammer",    
                        "°Ë±¦ÁÁÒø´¸"        :        "babao hammer",    
                ]),
        "sword"                :        
                ([
                        "ËÉÎÆ¹Å¶¨½£"        :        "guding sword",   
                        "ÆßĞÇöÌºç½£"        :        "liuhong sword",    
                        "ÁÒÑæÇà·æ½£"        :        "qingfeng sword",    
                        "Í¸Áú½£"        :        "toulong sword",    
                        "É¥ÃÅ±¦½£"        :        "sanmeng sword",    
                        "×ÏµçÇàËª½£"        :        "zidian sword",    
                        "×ÏËª½£"        :        "zishuang sword",    
                        "±ÌÁé½£"        :        "biling sword",    
                        "ÅÌÉß±¦½£"        :        "panshe sword",    
                        "ÅÌÁú±¦½£"        :        "panlong sword",    
                        "ÌìÀÇ½£"        :        "tianlang sword",    
                        "ÎÚ¹³½£"        :        "wugou sword",    
                        "Çà¸Ö½£"        :        "qinggang sword",    
                        "Ô§Ñì½£"        :        "yanyang sword",    
                        "ÇàÆ¼½£"        :        "qingping sword",    
                        "Ì«ºÏ½£"        :        "taihe sword",    
                        "ÈÕÔÂ»ğÁú½£"        :        "huolong sword",    
                        "ÇàÁú½£"        :        "qinglong sword",    
                        "ÖïÁú½£"        :        "zhulong sword",    
                        "À§Áú½£"        :        "kunlong sword",    
                        "º®¹â½£"        :        "hanguang sword",    
                        "ÁøÒ¶½£"        :        "liuye sword",    
                        "·ÖÌì½£"        :        "fentian sword",    
                        "ÂäÒ¶Çà·æ½£"        :        "luoye sword",   
                        "¶şÈĞÇà¸Ö½£"        :        "qinggang sword",    
                        "³¤ºç½£"        :        "changhong sword",   
                        "Õ¶ÏÉ½£"        :        "zhanxian sword",    
                        "ÎÚÁú½£"        :        "wulong sword",    
                        "ÇàÔÆ½£"        :        "qingyun sword",    
                        "Àæ»¨±¦½£"        :        "lihua sword",    
                        "°×¹â½£"        :        "baiguang sword",    
                        "²ÃÔÆ±¦½£"        :        "caiyun sword",    
                ]),
        "staff"                :        
                ([
                        "ÒõÑôÕÈ"        :        "yinyang staff",   
                        "óXäşÕÈ"        :        "lilai staff",  
                        "Ä«½ÇÕÈ"        :        "mojiao staff",  
                        "Å£½ÇÕÈ"        :        "niujiao staff",  
                        "¶ÀÁúÕÈ"        :        "dulong staff",  
                        "ÆßĞÇÎÔÓãÕÈ"        :        "woyu staff",  
                        "ïÙÌú¶¡×ÖÕÈ"        :        "dingzi staff",  
                        "ïÙÌú»³±§ÕÈ"        :        "huaibao staff",  
                        "ÁúÍ·ÕÈ"        :        "longtou staff",  
                        "»¢Í·ÕÈ"        :        "hutou staff", 
                        "ÆßĞÇÕÈ"        :        "qixing staff",  
                        "»¤ÊÖË«ÌúÕÈ"        :        "hushou staff",  
                        "Ô§ÑìÕÈ"        :        "yanyang staff",  
                        "µ¥µ¶ÎÔÓãÕÈ"        :        "woyu staff",  
                        "³ÁÏãÕÈ"        :        "chenxiang staff",  
                        "¹´Â§»¢Í·ÕÈ"        :        "goulou staff",  
                        "ïÙÌúÔ§ÑìÕÈ"        :        "yanyang staff", 
                ]),
        "club"                :        
                ([
                        "Ë®»ğÇôÁú°ô"        :        "qiulong club",   
                        "¿ªÉ½°ô"        :        "kaishan club", 
                        "¶¤¶¤ÀÇÑÀ°ô"        :        "dingding club", 
                        "Éø½ğİğŞ¼°ô"        :        "shenjin club", 
                        "×Ï½ğò°Áú°ô"        :        "zijin club", 
                        "ÎÚÓÍ°ô"        :        "wuyou club", 
                        "°ËÀâ°ô"        :        "baleng club", 
                        "ÁúÍ·Èí°ô"        :        "longtou club", 
                        "»ëÌú°ô"        :        "huntie club", 
                        "Ììî¸°ô"        :        "tiangang club", 
                        "¶ÀÁúÉø½ğ°ô"        :        "dulong club", 
                        "ĞĞÕß°ô"        :        "xingzhe club", 
                        "ÁÁÒøÀÇÑÀ°ô"        :        "langya club", 
                        "ÇàÍ­İğŞ¼°ô"        :        "qingtong club", 
                        "ïÙÌúÂİË¿°ô"        :        "luosi club", 
                        "½ğË¿ÌÙÉß°ô"        :        "tengshe club", 
                        "½ğ¹âÀÇÑÀ°ô"        :        "jinguang club", 
                        "°Ù¶¤ÀÇÑÀ°ô"        :        "baiding club", 
                        "×ÏÌÙÈí°ô"        :        "ziteng club", 
                        "ÇàÍ­°ôé³"        :        "qingtong club", 
                        "½ğË¿°ôé³"        :        "jinsi club",
                ]),
        "whip"                :        
                ([
                        "ÁÁÒø±Ş"        :        "liangyin whip",
                        "Öñ½Ú¸Ö±Ş"        :        "zhujie whip",
                        "±ªÎ²±Ş"        :        "baowei whip", 
                        "´ò½«±Ş"        :        "dajiang whip", 
                        "ÍÕ¹ÇÒõ·ç±Ş"        :        "tuogu whip", 
                        "½ğÁú±Ş"        :        "jinlong whip", 
                        "»¢Î²¸Ö±Ş"        :        "huwei whip", 
                        "ïÙÌú±Ş"        :        "bingtie whip", 
                        "ÁúÍ··ïÎ²±Ş"        :        "longtou whip", 
                        "»¢ÑÛ¸Ö±Ş"        :        "huyan whip", 
                        "½ğË¿Èí±Ş"        :        "jinsi whip", 
                        "ºùÂ«±Ş"        :        "hulu whip", 
                        "¹ê¹Ç±Ş"        :        "guigu whip", 
                        "ÓãÎ²±Ş"        :        "yugu whip", 
                        "Éß¹Ç±Ş"        :        "shegu whip", 
                        "ÒøË¿Èí±Ş"        :        "yinsi whip", 
                        "ÕÚÔÆÉ¨Áú±Ş"        :        "zheyun whip", 
                ]),

        "cloth"                :        
                ([
                        "Âé²¼ÒÂ"        :        "mabu cloth",
                        "ÃŞ²¼ÒÂ"        :        "mianbu cloth",
                        "³ñ²¼ÒÂ"        :        "choubu cloth",
                        "·ÉÑ©ÒÂ"        :        "feixue cloth",
                        "Ò¹Ä§ÒÂ"        :        "yemo cloth",
                        "ÇàË¿ÒÂ"        :        "qingsi cloth",
                        "¾ÅÌìÅÛ"        :        "jiutian cloth",
                        "ĞéÎŞÅÛ"        :        "xuwu cloth",
                        "ÇàÚ¤ÅÛ"        :        "qingming cloth",
                        "ÔÆÂŞÒÂ"        :        "yunluo cloth",
                        "Ë¿³ñ³¤ÅÛ"        :        "silk cloth",
                ]),
        "head"                :        
                ([
                        "ÄÖÁú´¹Í·"        :        "naolong kui",
                        "Ò¹Ã÷¿ø"        :        "yeming kui",
                        "·ï³á½ğ¿ø"        :        "fengchi kui",
                        "Í­ºÉÒ¶¿ø"        :        "heye kui",
                        "»Æ½ğË§×Ö¿ø"        :        "huangjin kui", 
                        "ÒøÁ·¿ø"        :        "yinlian kui",
                        "·ÖË®¿ø"        :        "fenshui kui",
                        "Îå·ï³¯Ñô¿ø"        :        "chaoyang kui", 
                        "·ï³áÔÂÃ÷¿ø"        :        "fengchi kui", 
                        "ÀÇÑÀ¿ø"        :        "langya kui", 
                        "Îå·ï»¨¿ø"        :        "wufeng kui", 
                        "Ì«Ëê¿ø"        :        "taisui kui", 
                        "×êÌì¿ø"        :        "zuantian kui",
                        "ÁÁÒø»¢Í·¿ø"        :        "hutou kui", 
                        "±ª×Ó¿ø"        :        "baozi kui", 
                        "ºûµû½ğ¿ø"        :        "hudie kui", 
                        "Ë«·ï¹Ú"        :        "shuangfeng guan", 
                        "½ğ·ï¹Ú"        :        "jinfeng guan",  
                        "³à½ğ¹Ú"        :        "chijin guan",  
                        "½ğÏ¼¹Ú"        :        "jinxia guan", 
                        "×Ï½ğ¹Ú"        :        "zijin guan",  
                        "Êø·¢½ğ¹Ú"        :        "shufa guan",  
                        "¾ÅÔÆÁÒÑæ¹Ú"        :        "lieyan guan", 
                ]),
        "neck"                :        
                ([
                        "ºÚºü¾±Á´"        :        "heihu necklace",
                        "Å®Éñ¾±Á´"        :        "nvshen necklace",
                        "ÒøÏîÁ´"        :        "yin necklace",
                        "Í­ÏîÁ´"        :        "tong necklace",
                        "½ğÏîÁ´"        :        "jin necklace",
                        "À¶ÓñÏîÁ´"        :        "lanyu necklace",
                        "»ÆË®¾§ÏîÁ´"        :        "shuijing necklace",
                        "ÇàÍ­ÏîÁ´"        :        "qingtong necklace",
                        "´ĞÍ·ÏîÁ´"        :        "congtou necklace",
                        "÷¼÷ÃÏîÁ´"        :        "kulou necklace",
                        "¹ÅÊ÷ÏîÁ´"        :        "gushu necklace",
                        "ôä´äÏîÁ´"        :        "feicui necklace",
                        "±ùÁÛÏîÁ´"        :        "binglin necklace",
                ]),
        "armor"                :
                ([
                        "ÁøÒ¶ÃàÖñîø"        :        "liuye armor",
                        "´óÒ¶ÓãÁÛ¼×"        :        "yulin armor",
                        "´óÒ¶ÁúÁÛ¼×"        :        "longlin armor",
                        "ïÙÌú¼×"        :        "bingtie armor", 
                        "³à½ğîø¼×"        :        "chijin armor", 
                        "»Æ½ğ¼×"        :        "huangjin armor",
                        "¹ê±³¼×"        :        "guibei armor",
                        "Ä«Óã¼×"        :        "moyu armor",
                        "³àÍ­´óÒ¶¼×"        :        "chitong armor",
                        "Òø×°¼×"        :        "yinzhuang armor", 
                        "Á¬»·ïÙÌúîø"        :        "lianhuan armor",
                        "ÔÂÂäºìÔÆ¼×"        :        "yueluo armor",
                        "½ğË¿Èí¼×"        :        "jinsi armor",
                        "×ÏÌÙ¼×"        :        "ziteng armor",
                        "×Ï½ğ»¤ĞÄ¼×"        :        "huxin armor", 
                        "ºÉÒ¶Á¬»·¼×"        :        "heye armor", 
                ]),
        "surcoat"        :        
                ([
                        "Ò¹¹âÅû·ç"        :        "yeguang pifeng",
                        "»Æ½ğÅû·ç"        :        "huangjin pifeng",
                        "Ãà²¼¶·Åñ"        :        "mianbu pifeng",
                        "ÑòÆ¤¶·Åñ"        :        "yangpi pifeng",
                        "³ñ¶Ğ¶·Åñ"        :        "chouduan pifeng",
                        "³àºì¶·Åñ"        :        "chihong pifeng",
                        "Áé½ÇÅû·ç"        :        "lingjiao pifeng",
                        "Õ½ÔÂÅû·ç"        :        "zhanyue pifeng",
                        "ÒìÊŞÅû·ç"        :        "yishou pifeng",
                ]),
        "waist"                :        
                ([
                        "·«²¼Ñü´ø"        :        "fanbu waist",
                        "ÕæÆ¤Ñü´ø"        :        "zhenpi waist",
                        "±àÖ¯Ñü´ø"        :        "bianzhi waist",
                        "´Ö²¼Ñü´ø"        :        "cubu waist",
                        "ÉúÌúÑü´ø"        :        "shengtie waist",
                        "çúçêÑü´ø"        :        "hupo waist",
                        "±ùÁÛÑü´ø"        :        "binglin waist",
                        "°×ÒøÑü´ø"        :        "baiying waist",
                        "ôä´äÑü´ø"        :        "feicui waist",
                ]),
        "wrists"        :        
                ([
                        "´Ö²¼»¤Íó"        :        "cubu wrists",
                        "×ÏÖñ»¤Íó"        :        "zizhu wrists",
                        "¹ÅÄ¾»¤Íó"        :        "gumu wrists",
                        "ÇàÍ­»¤Íó"        :        "qingtong wrists",
                        "¾«Ìú»¤Íó"        :        "jingtie wrists",
                        "ôä´ä»¤Íó"        :        "feicui wrists",
                        "»Æ½ğ»¤Íó"        :        "huangjin wrists",
                        "±ùÁÛ»¤Íó"        :        "bingling wrists",
                ]),
        "finger"        :
                ([
                        "ÓÀºã½äÖ¸"        :        "yongheng ring",
                        "»¨½äÖ¸"        :        "hua ring",
                        "Òø½äÖ¸"        :        "yin ring",
                        "ÍşÑÏ½äÖ¸"        :        "weiyan ring",
                        "Ê×Áì½äÖ¸"        :        "shouling ring",
                        "¹ÅÊ÷½äÖ¸"        :        "gushu ring",
                        "ÒşÊ¿½äÖ¸"        :        "yinshi ring",
                        "Ê®×Ö¹Ç½ä"        :        "shizi ring",
                        "Ë®¾§½äÖ¸"        :        "shuijing ring",
                        "±ùÁÛ½äÖ¸"        :        "bingling ring",
                        "ôä´ä½äÖ¸"        :        "feicui ring",
                        "·ÉÑ©½äÖ¸"        :        "feixue ring",
                        "×ÏÖñ½äÖ¸"        :        "zizhu ring",
                        "ÊŞ¹Ç½äÖ¸"        :        "shougu ring",
                ]),
        "hands"                :        
                ([
                        "Á÷ÔÆÊÖÌ×"        :        "liuyun glove",
                        "³àÁ¶ÊÖÌ×"        :        "chilian glove",
                        "ĞéÎŞÊÖÌ×"        :        "xuwu glove",
                        "ïÖ½ğÊÖÌ×"        :        "liujin glove",
                        "ïÙÌúÊÖÌ×"        :        "bingtie glove",
                ]),
        "boots"                :        
                ([
                        "Á÷ÔÆÑ¥"        :        "liuyun shoes",
                        "³àÁ¶Ñ¥"        :        "chilian shoes",
                        "ĞéÎŞÑ¥"        :        "xuwu shoes",
                        "ïÖ½ğÑ¥"        :        "liujin shoes",
                        "»ğÁúÑ¥"        :        "huolong shoes",
                        "ÊŞÆ¤Ñ¥"        :        "shoupi shoes",
                        "Í­ÑÀÑ¥"        :        "tongya shoes",
                        "¾«ÌúÑ¥"        :        "jingtie shoes",
                        "³Ë·çÑ¥"        :        "chengfeng shoes",
                        "»¢ÎÆÑ¥"        :        "huwen shoes",
                        "ÆÆÀËÑ¥"        :        "polang shoes",
                ]),
]);
