#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "zhenzhu",
                "name":        "´óÕäÖé",
                "type":        "Ñ°",
                "bonus":       85,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/zhenzhu.c",
        ]),
        ([
                "id":          "dodgebook",
                "name":        "Çá¹¦Æª",
                "type":        "Ñ°",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/yanziwu/obj/dodgebook.c",
        ]),
        ([
                "id":          "green cloth",
                "name":        "[1;32mÇà²¼ÒÂ[2;37;0m",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/green_cloth.c",
        ]),
        ([
                "id":          "bian dan",
                "name":        "ÊìÌú±âµ£",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/biandan.c",
        ]),
        ([
                "id":          "tiepipa",
                "name":        "[1;36mÌúÅýÅÃ[2;37;0m",
                "type":        "Ñ°",
                "bonus":       53,
                "msg1":        "",
                "object":      "/d/guanwai/npc/obj/tiepipa.c",
        ]),
        ([
                "id":          "pink cloth",
                "name":        "·Ûºì³ñÉÀ",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/fuzhou/obj/pink_cloth.c",
        ]),
        ([
                "id":          "pangguan bi",
                "name":        "[1;36mÅÐ¹Ù±Ê[2;37;0m",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/bi.c",
        ]),
        ([
                "id":          "da dao",
                "name":        "´óµ¶",
                "type":        "Ñ°",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/dadao.c",
        ]),
        ([
                "id":          "card1",
                "name":        "·çÀ×ÌÃÁîÅÆ",
                "type":        "Ñ°",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/card1.c",
        ]),
        ([
                "id":          "jian dao",
                "name":        "¼âµ¶",
                "type":        "Ñ°",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/jiandao.c",
        ]),
        ([
                "id":          "tongren",
                "name":        "[1;33m¶À½ÅÍ­ÈË[2;37;0m",
                "type":        "Ñ°",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/guanwai/npc/obj/tongren.c",
        ]),
        ([
                "id":          "fuchen",
                "name":        "·÷³¾",
                "type":        "Ñ°",
                "bonus":       92,
                "msg1":        "",
                "object":      "/d/quanzhou/obj/fuchen.c",
        ]),
        ([
                "id":          "gebu changpao",
                "name":        "¸ð²¼³¤ÅÛ",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/changpao.c",
        ]),
        ([
                "id":          "changjian",
                "name":        "³¤½£",
                "type":        "Ñ°",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/changjian.c",
        ]),
        ([
                "id":          "zhe shan",
                "name":        "ÓÍÖ½ÕÛÉÈ",
                "type":        "Ñ°",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/zheshan.c",
        ]),
        ([
                "id":          "gan cheng",
                "name":        "¸Ë³Ó",
                "type":        "Ñ°",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/gancheng.c",
        ]),
        ([
                "id":          "fu",
                "name":        "¿³²ñ¸«",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/axe.c",
        ]),
        ([
                "id":          "tie zhang",
                "name":        "[37m¾«ÌúÕÈ[2;37;0m",
                "type":        "Ñ°",
                "bonus":       81,
                "msg1":        "",
                "object":      "/d/tulong/yitian/npc/obj/tiezhang.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "ºÚÉ«²¼ÒÂ",
                "type":        "Ñ°",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/henshan/npc/obj/blackcloth.c",
        ]),
        ([
                "id":          "zijin chui",
                "name":        "×Ï½ð´¸",
                "type":        "Ñ°",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/zijinchui.c",
        ]),
        ([
                "id":          "gangzhang",
                "name":        "¸ÖÕÈ",
                "type":        "Ñ°",
                "bonus":       85,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/gangzhang.c",
        ]),
        ([
                "id":          "changbian",
                "name":        "Ìú±Þ",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/hangzhou/honghua/obj/tiebian.c",
        ]),
        ([
                "id":          "jiasha",
                "name":        "[1;33m»ÆÉ«ôÂôÄ[2;37;0m",
                "type":        "Ñ°",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/xueshan/obj/y-jiasha.c",
        ]),
        ([
                "id":          "seng mao",
                "name":        "[1;31mÉ®Ã±[2;37;0m",
                "type":        "Ñ°",
                "bonus":       70,
                "msg1":        "",
                "object":      "/d/xueshan/obj/sengmao.c",
        ]),
        ([
                "id":          "tong bo",
                "name":        "[33mÍ­îà[2;37;0m",
                "type":        "Ñ°",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/tulong/yitian/npc/obj/tongbo.c",
        ]),
        ([
                "id":          "shoufa tu1",
                "name":        "ÌìÉ½ÕÛÃ·ÊÖ·¨Í¼ÉÏ¾í",
                "type":        "Ñ°",
                "bonus":       85,
                "msg1":        "",
                "object":      "/clone/book/zhemei_book1.c",
        ]),
        ([
                "id":          "shoufa tu2",
                "name":        "ÌìÉ½ÕÛÃ·ÊÖ·¨Í¼ÏÂ¾í",
                "type":        "Ñ°",
                "bonus":       85,
                "msg1":        "",
                "object":      "/clone/book/zhemei_book2.c",
        ]),
        ([
                "id":          "ruanwei jia",
                "name":        "Èíâ¬¼×",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/taohua/obj/ruanwei.c",
        ]),
        ([
                "id":          "pao",
                "name":        "[37m»ÒÉ«µÀÅÛ[2;37;0m",
                "type":        "Ñ°",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/quanzhen/npc/obj/grayrobe.c",
        ]),
        ([
                "id":          "shan",
                "name":        "Çà²¼³¤ÉÀ",
                "type":        "Ñ°",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/wudang/obj/bluecloth.c",
        ]),
        ([
                "id":          "pao",
                "name":        "ÇàÉ«µÀÅÛ",
                "type":        "Ñ°",
                "bonus":       92,
                "msg1":        "",
                "object":      "/d/wudang/obj/greenrobe.c",
        ]),
        ([
                "id":          "jindai",
                "name":        "Êø·¢½ð´ø",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/taohua/obj/shudai.c",
        ]),
        ([
                "id":          "pi beixin",
                "name":        "Æ¤±³ÐÄ",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/city/obj/beixin.c",
        ]),
        ([
                "id":          "armor",
                "name":        "Ìú¼×",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/city/npc/obj/tiejia.c",
        ]),
        ([
                "id":          "zhan armor",
                "name":        "Õ½¼×",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/zhanjia.c",
        ]),
        ([
                "id":          "skirt",
                "name":        "ÇáÉ´³¤È¹",
                "type":        "Ñ°",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/skirt.c",
        ]),
        ([
                "id":          "seng pao",
                "name":        "[1;33mÉ®ÅÛ[2;37;0m",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/sengpao.c",
        ]),
        ([
                "id":          "hammer",
                "name":        "Ìú´¸",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/hammer.c",
        ]),
        ([
                "id":          "changbian",
                "name":        "³¤±Þ",
                "type":        "Ñ°",
                "bonus":       79,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/changbian.c",
        ]),
        ([
                "id":          "fu chen",
                "name":        "·÷³¾",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/fuchen.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "[1;37m°×É«³¤ÉÀ[2;37;0m",
                "type":        "Ñ°",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/cloth4.c",
        ]),
        ([
                "id":          "chang pao",
                "name":        "°×É«³¤ÅÛ",
                "type":        "Ñ°",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/baituo/obj/baipao.c",
        ]),
        ([
                "id":          "diao gan",
                "name":        "µö¸Ë",
                "type":        "Ñ°",
                "bonus":       77,
                "msg1":        "",
                "object":      "/kungfu/class/dali/obj/diaogan.c",
        ]),
});
mapping query_questkh()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
