#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "wo kou",
                "name":        "Ÿ¡ø‹",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/taiwan/npc/wokou.c",
        ]),
        ([
                "id":          "wang furen",
                "name":        "Õı∑Ú»À",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/fuzhou/npc/wang.c",
        ]),
        ([
                "id":          "pu ren",
                "name":        "∆Õ»À",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/emei/npc/puren.c",
        ]),
        ([
                "id":          "zu zhang",
                "name":        "◊Â≥§",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/zuzhang.c",
        ]),
        ([
                "id":          "zhao min",
                "name":        "’‘√Ù",
                "type":        "…±",
                "bonus":       83,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhaomin2.c",
        ]),
        ([
                "id":          "zhao min",
                "name":        "’‘√Ù",
                "type":        "…±",
                "bonus":       86,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhao.c",
        ]),
        ([
                "id":          "jiang baisheng",
                "name":        "Ω≠∞Ÿ §",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taishan/npc/jiang.c",
        ]),
        ([
                "id":          "lao fuzi",
                "name":        "¿œ∑Ú◊”",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/suzhou/npc/jiaoxi.c",
        ]),
        ([
                "id":          "yafu",
                "name":        "—∆∏æ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hengshan/npc/yafu.c",
        ]),
        ([
                "id":          "shi tong",
                "name":        " ÃÕØ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taohua/npc/shitong.c",
        ]),
        ([
                "id":          "tianbai daoren",
                "name":        "ÃÏ∞ÿµ¿»À",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/taishan/tianbai.c",
        ]),
        ([
                "id":          "meng jianxiong",
                "name":        "√œΩ°–€",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/meng.c",
        ]),
        ([
                "id":          "ha dani",
                "name":        "π˛¥Ôƒ·",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/guanwai/npc/hadani.c",
        ]),
        ([
                "id":          "lin zhennan",
                "name":        "¡÷’ƒœ",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/fuzhou/npc/linzhennan.c",
        ]),
        ([
                "id":          "jianchu daoren",
                "name":        "Ω®≥˝µ¿»À",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/taishan/npc/jianchu.c",
        ]),
        ([
                "id":          "zhangli",
                "name":        "’∆¿Ìµ¿≥§",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/quanzhen/npc/zhangli.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "º“∂°",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/guiyun/npc/jiading.c",
        ]),
        ([
                "id":          "fan yifei",
                "name":        "∑∂“ª∑…",
                "type":        "…±",
                "bonus":       86,
                "msg":        "",
                "object":      "/d/yixing/npc/fanyifei.c",
        ]),
        ([
                "id":          "menggu bing",
                "name":        "√…π≈±¯",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/xiangyang/npc/menggubing.c",
        ]),
        ([
                "id":          "cheng chaofeng",
                "name":        "≥Ã≥∞∑Á",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/mingjiao/npc/chengchaofeng.c",
        ]),
        ([
                "id":          "lu dayou",
                "name":        "¬Ω¥Û”–",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/dayou.c",
        ]),
        ([
                "id":          "zuo jiang",
                "name":        "◊ÙΩ´",
                "type":        "…±",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/xiangyang/npc/zuo.c",
        ]),
        ([
                "id":          "ya jiang",
                "name":        "—¿Ω´",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/xiangyang/npc/ya.c",
        ]),
        ([
                "id":          "ya pu",
                "name":        "—∆∆Õ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taohua/npc/yapu.c",
        ]),
        ([
                "id":          "tianyi daoren",
                "name":        "ÃÏ““µ¿»À",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/taishan/tianyi.c",
        ]),
        ([
                "id":          "tiansong daoren",
                "name":        "ÃÏÀ…µ¿»À",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/taishan/tiansong.c",
        ]),
        ([
                "id":          "zhen youqing",
                "name":        "’Á”–«Ï",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/suzhou/npc/shiye.c",
        ]),
        ([
                "id":          "an jiangang",
                "name":        "∞≤Ω°∏’",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/an.c",
        ]),
        ([
                "id":          "jin bing",
                "name":        "¥ÛΩ±¯",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/guiyun/npc/jinbing.c",
        ]),
        ([
                "id":          "feng liang",
                "name":        "∑Á¡º",
                "type":        "…±",
                "bonus":       81,
                "msg":        "",
                "object":      "/d/yixing/npc/fengliang.c",
        ]),
        ([
                "id":          "maimaiti",
                "name":        "¬Ú¬ÙÃ·",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xingxiu/npc/maimaiti.c",
        ]),
        ([
                "id":          "tuo lei",
                "name":        "Õœ¿◊",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/xiangyang/npc/tuolei.c",
        ]),
        ([
                "id":          "pi jiang",
                "name":        "Ò‘Ω´",
                "type":        "…±",
                "bonus":       76,
                "msg":        "",
                "object":      "/d/xiangyang/npc/pi.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "«‡“¬Œ‰ ø",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi3.c",
        ]),
        ([
                "id":          "yun sumei",
                "name":        "‘∆Àÿ√∑",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/shenlong/npc/yunsumei.c",
        ]),
        ([
                "id":          "wu shi",
                "name":        "“ª∆∑Ã√Œ‰ ø",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/lingzhou/npc/yipinwushi.c",
        ]),
        ([
                "id":          "wu shi",
                "name":        " Ø»ÀŒ‰ ø",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/lingzhou/npc/shiwushi.c",
        ]),
        ([
                "id":          "yi lin",
                "name":        "“«¡’",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/henshan/npc/yilin.c",
        ]),
        ([
                "id":          "feng yiming",
                "name":        "∑Ô“ª√˘",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/foshan/npc/fengyiming.c",
        ]),
        ([
                "id":          "gaoli shang",
                "name":        "∏ﬂ¿ˆ…Ã",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/xiangyang/npc/gaoli.c",
        ]),
        ([
                "id":          "sun baopi",
                "name":        "ÀÔ∞˛∆§",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/suzhou/npc/sun.c",
        ]),
        ([
                "id":          "feng zhengdong",
                "name":        "∑Î’˝∂´",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/suzhou/npc/feng.c",
        ]),
        ([
                "id":          "hongmao gui",
                "name":        "∫Ï√´πÌ",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/taiwan/npc/hongmao.c",
        ]),
        ([
                "id":          "zhangyao",
                "name":        "’∆“©µ¿≥§",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/quanzhen/npc/zhangyao.c",
        ]),
        ([
                "id":          "xiao wei",
                "name":        "–£Œæ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xiaowei.c",
        ]),
        ([
                "id":          "gao genming",
                "name":        "∏ﬂ∏˘√˜",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/huashan/npc/gao-genming.c",
        ]),
        ([
                "id":          "xianghuo daoren",
                "name":        "œ„ªµ¿»À",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/npc/xianghuo.c",
        ]),
        ([
                "id":          "zhong wanchou",
                "name":        "÷”ÕÚ≥",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/zhong.c",
        ]),
        ([
                "id":          "feng",
                "name":        "∑ÎÃ˙Ω≥",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/village/npc/smith.c",
        ]),
        ([
                "id":          "zhou yi",
                "name":        "÷‹Á≤",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/zhouyi.c",
        ]),
        ([
                "id":          "lu zhengping",
                "name":        "¬¿’˝∆Ω",
                "type":        "…±",
                "bonus":       83,
                "msg":        "",
                "object":      "/d/yixing/npc/luzhengping.c",
        ]),
        ([
                "id":          "gao san",
                "name":        "∏ﬂ»˝ƒÔ◊”",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/yixing/npc/gaosan.c",
        ]),
        ([
                "id":          "guo fu",
                "name":        "π˘‹Ω",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/guofu.c",
        ]),
        ([
                "id":          "gan baobao",
                "name":        "∏ ±¶±¶",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/gan.c",
        ]),
        ([
                "id":          "pu ren",
                "name":        "∆Õ»À",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taohua/npc/puren.c",
        ]),
        ([
                "id":          "zhao min",
                "name":        "’‘√Ù",
                "type":        "…±",
                "bonus":       83,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/zhaomin.c",
        ]),
        ([
                "id":          "liang fa",
                "name":        "¡∫∑¢",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/liang-fa.c",
        ]),
        ([
                "id":          "lao xiucai",
                "name":        "¿œ–„≤≈",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/yongdeng/npc/xiucai.c",
        ]),
        ([
                "id":          "tuoba",
                "name":        "Õÿ∞œ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/mingjiao/npc/tuoba.c",
        ]),
        ([
                "id":          "gao shanwang",
                "name":        "∏ﬂ…ΩÕı",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/mingjiao/npc/gaoshanwang.c",
        ]),
        ([
                "id":          "feng gongying",
                "name":        "∑‚π≠”∞",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/mingjiao/npc/fenggongying.c",
        ]),
        ([
                "id":          "shi daizi",
                "name":        " ©¥˜◊”",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/shi-daizi.c",
        ]),
        ([
                "id":          "ji qingxu",
                "name":        "ºß«Â–È",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/ji.c",
        ]),
        ([
                "id":          "xiao zhao",
                "name":        "–°’—",
                "type":        "…±",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/mingjiao/xiaozhao.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "Ωı“¬Œ¿ ø",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/weishi2.c",
        ]),
        ([
                "id":          "daizu shouling",
                "name":        "¥ˆ◊Â ◊¡Ï",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/dali/npc/shouling.c",
        ]),
        ([
                "id":          "po yi",
                "name":        "∆∆“…",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/dali/npc/poyi.c",
        ]),
        ([
                "id":          "po chen",
                "name":        "∆∆‡¡",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/dali/npc/pochen.c",
        ]),
        ([
                "id":          "lao jisi",
                "name":        "¿œº¿Àæ",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/jisi1.c",
        ]),
        ([
                "id":          "ji si",
                "name":        "º¿Àæ",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/dali/npc/jisi.c",
        ]),
        ([
                "id":          "jianghu yiren",
                "name":        "Ω≠∫˛“’»À",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/jianghuyiren.c",
        ]),
        ([
                "id":          "duan wuwei",
                "name":        "∂ŒŒﬁŒ∑",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/duanwuwei.c",
        ]),
        ([
                "id":          "wu tiande",
                "name":        "Œ‚ÃÏµ¬",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/wutiande.c",
        ]),
        ([
                "id":          "tang huai",
                "name":        "Ã∆ª±",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/tanghuai.c",
        ]),
        ([
                "id":          "tang",
                "name":        "Ã∆’∆πÒ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/tanghua.c",
        ]),
        ([
                "id":          "cheng yuhuan",
                "name":        "≥Ã”Òª∑",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/city/npc/yuhuan.c",
        ]),
        ([
                "id":          "xian laoban",
                "name":        "Ÿ˛¿œ∞Â",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/city/npc/xian.c",
        ]),
        ([
                "id":          "wei chunfang",
                "name":        "Œ§¥∫∑º",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/city/npc/wei.c",
        ]),
        ([
                "id":          "tan youji",
                "name":        "Ã∑”—ºÕ",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/city/npc/shiye.c",
        ]),
        ([
                "id":          "mao shiba",
                "name":        "√© Æ∞À",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/city/npc/mao18.c",
        ]),
        ([
                "id":          "gui gong",
                "name":        "πÍπ´",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/city/npc/guigong.c",
        ]),
        ([
                "id":          "cheng yaofa",
                "name":        "≥Ã“©∑¢",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/city/npc/cheng.c",
        ]),
        ([
                "id":          "liang xinglu",
                "name":        "¡∫–À¬ª",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/zhifu.c",
        ]),
        ([
                "id":          "yang laoban",
                "name":        "—Ó¿œ∞Â",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/yang-laoban.c",
        ]),
        ([
                "id":          "li boyuan",
                "name":        "¿Ó≤©‘®",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/xueshi.c",
        ]),
        ([
                "id":          "xiang ke",
                "name":        "œ„øÕ",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/changan/npc/xiangke.c",
        ]),
        ([
                "id":          "tie gongji",
                "name":        "Ã˙π´º¶",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/tiegongji.c",
        ]),
        ([
                "id":          "tang",
                "name":        "ÃÀ◊” ÷",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/tang.c",
        ]),
        ([
                "id":          "shu chi",
                "name":        " È≥’",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/shuchi.c",
        ]),
        ([
                "id":          "chen jisheng",
                "name":        "≥¬ºÃ ¢",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/shiye.c",
        ]),
        ([
                "id":          "monk",
                "name":        "÷™øÕ∫Õ…–",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/changan/npc/monk.c",
        ]),
        ([
                "id":          "liu laoshi",
                "name":        "¡ı¿œ µ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/liu.c",
        ]),
        ([
                "id":          "jin fuhuan",
                "name":        "Ω∏¥ªπ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/jinfuhuan.c",
        ]),
        ([
                "id":          "shuang er",
                "name":        "À´∂˘",
                "type":        "…±",
                "bonus":       86,
                "msg":        "",
                "object":      "/d/beijing/npc/shuanger.c",
        ]),
        ([
                "id":          "qi biaoqing",
                "name":        "∆Ó±Î«Â",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/qibiaoqing.c",
        ]),
        ([
                "id":          "qian laoben",
                "name":        "«Æ¿œ±æ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/qianlaoben.c",
        ]),
        ([
                "id":          "li lishi",
                "name":        "¿Ó¡¶ ¿",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/beijing/npc/lilishi.c",
        ]),
        ([
                "id":          "kang qinwang",
                "name":        "øµ«◊Õı",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/kangqinwang.c",
        ]),
        ([
                "id":          "guan anji",
                "name":        "πÿ∞≤ª˘",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/guananji.c",
        ]),
        ([
                "id":          "fan gang",
                "name":        "∑Æ∏Ÿ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/fangang.c",
        ]),
        ([
                "id":          "feng asan",
                "name":        "∑Î∞¢»˝",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/fengas.c",
        ]),
        ([
                "id":          "qingxu daozhang",
                "name":        "«Â–Èµ¿≥§",
                "type":        "…±",
                "bonus":       96,
                "msg":        "",
                "object":      "/kungfu/class/wudang/qingxu.c",
        ]),
        ([
                "id":          "huizhen zunzhe",
                "name":        "ª€’Ê◊’ﬂ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-zhen.c",
        ]),
        ([
                "id":          "huixu zunzhe",
                "name":        "ª€–È◊’ﬂ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-xu.c",
        ]),
        ([
                "id":          "huixiu zunzhe",
                "name":        "ª€–ﬁ◊’ﬂ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-xiu.c",
        ]),
        ([
                "id":          "huise zunzhe",
                "name":        "ª€…´◊’ﬂ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-se.c",
        ]),
        ([
                "id":          "huiru zunzhe",
                "name":        "ª€»Á◊’ﬂ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-ru.c",
        ]),
        ([
                "id":          "huiming zunzhe",
                "name":        "ª€√˚◊’ﬂ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-ming.c",
        ]),
        ([
                "id":          "huikong zunzhe",
                "name":        "ª€ø’◊’ﬂ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-kong.c",
        ]),
        ([
                "id":          "huijie zunzhe",
                "name":        "ª€Ω‡◊’ﬂ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-jie.c",
        ]),
        ([
                "id":          "huihe zunzhe",
                "name":        "ª€∫œ◊’ﬂ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/hui-he.c",
        ]),
        ([
                "id":          "mo bushou",
                "name":        "ƒ™≤ª ’",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/mo-bu.c",
        ]),
        ([
                "id":          "su mengqing",
                "name":        "À’√Œ«Â",
                "type":        "…±",
                "bonus":       96,
                "msg":        "",
                "object":      "/kungfu/class/emei/su.c",
        ]),
        ([
                "id":          "li mingxia",
                "name":        "¿Ó√˜œº",
                "type":        "…±",
                "bonus":       96,
                "msg":        "",
                "object":      "/kungfu/class/emei/li.c",
        ]),
        ([
                "id":          "fang bilin",
                "name":        "∑Ω±Ã¡’",
                "type":        "…±",
                "bonus":       96,
                "msg":        "",
                "object":      "/kungfu/class/emei/fang.c",
        ]),
});
mapping query_questkh()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
string *get_questname()
{
        int i;
        string *result = ({});
        
        for (i = 0; i < sizeof(quest);i ++)
                result += ({ quest[i]["name"] });
                
        return result;
}
