#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "wu jiang",
                "name":        "Îä½«",
                "type":        "É±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/xingxiu/npc/wujiang.c",
        ]),
        ([
                "id":          "li sao",
                "name":        "ÀîÉ©",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/lingjiu/npc/lisao.c",
        ]),
        ([
                "id":          "hao jie",
                "name":        "Ì«ºþºÀ½Ü",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guiyun/npc/haojie.c",
        ]),
        ([
                "id":          "zu touren",
                "name":        "×åÍ·ÈË",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/dali/npc/zutouren.c",
        ]),
        ([
                "id":          "wu santong",
                "name":        "ÎäÈýÍ¨",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wusantong.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "Ã½ÆÅ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/suzhou/npc/meipo.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "Îä½«",
                "type":        "É±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/hanzhong/npc/wujiang.c",
        ]),
        ([
                "id":          "zhuang zheng",
                "name":        "×¯ï£",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/zhuangzheng.c",
        ]),
        ([
                "id":          "yue lingshan",
                "name":        "ÔÀÁéÉº",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huashan/npc/yue-lingshan.c",
        ]),
        ([
                "id":          "liu jing",
                "name":        "ÁõÝ¼",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/henshan/npc/liujing.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "°×ÒÂÎäÊ¿",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi1.c",
        ]),
        ([
                "id":          "shi sao",
                "name":        "Ê¯É©",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/shisao.c",
        ]),
        ([
                "id":          "cheng qingshuang",
                "name":        "³ÌÇàËª",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/cheng.c",
        ]),
        ([
                "id":          "xin yan",
                "name":        "ÐÄÑâ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/xinyan.c",
        ]),
        ([
                "id":          "san hu",
                "name":        "ºöÂ×Èý»¢",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sanhu.c",
        ]),
        ([
                "id":          "wang jian",
                "name":        "Íõ¼á",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wang.c",
        ]),
        ([
                "id":          "zhou dian",
                "name":        "ÖÜµß",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/zhoudian.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "»Ê¹¬ÎÀÊ¿",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/lingzhou/npc/gongweishi.c",
        ]),
        ([
                "id":          "zu qianqiu",
                "name":        "×æÇ§Çï",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huanghe/npc/zu.c",
        ]),
        ([
                "id":          "youfang daoren",
                "name":        "ÓÎ·½µÀÈË",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/npc/youfang.c",
        ]),
        ([
                "id":          "er hu",
                "name":        "ºöÂ×¶þ»¢",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/erhu.c",
        ]),
        ([
                "id":          "da hu",
                "name":        "ºöÂ×´ó»¢",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/dahu.c",
        ]),
        ([
                "id":          "liu guoxuan",
                "name":        "Áõ¹úÐù",
                "type":        "É±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/taiwan/npc/liu.c",
        ]),
        ([
                "id":          "zhang zhong",
                "name":        "ÕÅÖÐ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/zhangzhong.c",
        ]),
        ([
                "id":          "xin ran",
                "name":        "ÐÁÈ»",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/xinran.c",
        ]),
        ([
                "id":          "wen cangsong",
                "name":        "ÎÅ²ÔËÉ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/wensong.c",
        ]),
        ([
                "id":          "shuo bude",
                "name":        "Ëµ²»µÃ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/shuobude.c",
        ]),
        ([
                "id":          "li tianyuan",
                "name":        "ÀîÌìÔ«",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/litianyuan.c",
        ]),
        ([
                "id":          "leng qian",
                "name":        "ÀäÇ«",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/lengqian.c",
        ]),
        ([
                "id":          "yun zhonghe",
                "name":        "ÔÆÖÐº×",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/lingzhou/npc/yun.c",
        ]),
        ([
                "id":          "luo bing",
                "name":        "Âæ±ù",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/luo.c",
        ]),
        ([
                "id":          "jiang sigen",
                "name":        "½¯ËÄ¸ù",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/jiang.c",
        ]),
        ([
                "id":          "sun popo",
                "name":        "ËïÆÅÆÅ",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/gumu/npc/sun.c",
        ]),
        ([
                "id":          "ding jian",
                "name":        "¶¡¼á",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/meizhuang/ding.c",
        ]),
        ([
                "id":          "wu xiuwen",
                "name":        "ÎäÐÞÎÄ",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wuxiuwen.c",
        ]),
        ([
                "id":          "yao hou",
                "name":        "ÀÖºñ",
                "type":        "É±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/songshan/yao.c",
        ]),
        ([
                "id":          "zhu ziliu",
                "name":        "Öì×ÓÁø",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/zhuziliu.c",
        ]),
        ([
                "id":          "pian jiang",
                "name":        "Æ«½«",
                "type":        "É±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/xiangyang/npc/pian.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "ºìÒÂÎäÊ¿",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi2.c",
        ]),
        ([
                "id":          "yin wushou",
                "name":        "ÒóÎÞÊÙ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/yinwushou.c",
        ]),
        ([
                "id":          "yin wufu",
                "name":        "ÒóÎÞ¸£",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/yinwufu.c",
        ]),
        ([
                "id":          "yan yuan",
                "name":        "ÑÕÔ«",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/yanyuan.c",
        ]),
        ([
                "id":          "lu guanying",
                "name":        "Â½¹ÚÓ¢",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/guiyun/npc/xiaolu.c",
        ]),
        ([
                "id":          "wanyan kang",
                "name":        "ÍêÑÕ¿µ",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/d/guiyun/npc/wanyankang.c",
        ]),
        ([
                "id":          "lu guanying",
                "name":        "Â½¹ÚÓ¢",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/guiyun/npc/xiaolu.c",
        ]),
        ([
                "id":          "si hu",
                "name":        "ºöÂ×ËÄ»¢",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sihu.c",
        ]),
        ([
                "id":          "huta seng",
                "name":        "»¤ËþÉ®",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/hutaseng1.c",
        ]),
        ([
                "id":          "shou mu",
                "name":        "ÊØÄ¹¼ÒÅ«",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/taohua/npc/shoumu.c",
        ]),
        ([
                "id":          "tang yang",
                "name":        "ÌÆÑó",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/tangyang.c",
        ]),
        ([
                "id":          "peng yingyu",
                "name":        "ÅíÓ¨Óñ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/pengyingyu.c",
        ]),
        ([
                "id":          "hu qingniu",
                "name":        "ºúÇàÅ£",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/mingjiao/npc/hu.c",
        ]),
        ([
                "id":          "nu erhai",
                "name":        "Å¬¶ùº£",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/lingzhou/npc/nuerhai.c",
        ]),
        ([
                "id":          "yin yewang",
                "name":        "ÒóÒ°Íõ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/yinyewang.c",
        ]),
        ([
                "id":          "yin wulu",
                "name":        "ÒóÎÞÂ»",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/yinwulu.c",
        ]),
        ([
                "id":          "shen zhifan",
                "name":        "ÉêÖ¾·²",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/shen.c",
        ]),
        ([
                "id":          "qi zhicheng",
                "name":        "ÆîÖ¾³Ï",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/qi.c",
        ]),
        ([
                "id":          "pi qingxuan",
                "name":        "Æ¤ÇåÐþ",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/pi.c",
        ]),
        ([
                "id":          "li zhichang",
                "name":        "ÀîÖ¾³£",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/li.c",
        ]),
        ([
                "id":          "fang zhiqi",
                "name":        "·¿Ö¾Æð",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/fang.c",
        ]),
        ([
                "id":          "cui zhifang",
                "name":        "´ÞÖ¾·½",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/cui.c",
        ]),
        ([
                "id":          "cheng yaojia",
                "name":        "³ÌÑþåÈ",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/cheng.c",
        ]),
        ([
                "id":          "ping si",
                "name":        "Æ½ËÄ",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/hu/pingsi.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "Îä½«",
                "type":        "É±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/jiang.c",
        ]),
        ([
                "id":          "huo xiansheng",
                "name":        "»ôÏÈÉú",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/dali/npc/huo.c",
        ]),
        ([
                "id":          "da tusi",
                "name":        "´óÍÁË¾",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/dali/npc/datusi.c",
        ]),
        ([
                "id":          "shi cong",
                "name":        "ÊÌ´Ó",
                "type":        "É±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/chengdu/npc/shicong.c",
        ]),
        ([
                "id":          "qin bing",
                "name":        "Ç×±ø",
                "type":        "É±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/chengdu/npc/qinbing.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "Îä½«",
                "type":        "É±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/city/npc/wujiang.c",
        ]),
        ([
                "id":          "yulin jun",
                "name":        "ÓùÁÖ¾ü",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/d/changan/npc/yulinjun.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "Îä½«",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/wujiang.c",
        ]),
        ([
                "id":          "murong hao",
                "name":        "Ä½ÈÝºÀ",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/changan/npc/murong-hao.c",
        ]),
        ([
                "id":          "jing xuan",
                "name":        "¾»Ðþ",
                "type":        "É±",
                "bonus":       79,
                "msg":        "",
                "object":      "/d/changan/npc/jingxuan.c",
        ]),
        ([
                "id":          "jing ming",
                "name":        "¾»Ã÷",
                "type":        "É±",
                "bonus":       79,
                "msg":        "",
                "object":      "/d/changan/npc/jingming.c",
        ]),
        ([
                "id":          "da shou",
                "name":        "´òÊÖ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/dashou.c",
        ]),
        ([
                "id":          "chen laoban",
                "name":        "³ÂÀÏ°å",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/chen-laoban.c",
        ]),
        ([
                "id":          "bu tou",
                "name":        "²¶Í·",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/butou.c",
        ]),
        ([
                "id":          "zhao qixian",
                "name":        "ÕÔÆëÏÍ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/beijing/npc/zhaoqi.c",
        ]),
        ([
                "id":          "zhang kangnian",
                "name":        "ÕÅ¿µÄê",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/beijing/npc/zhangkang.c",
        ]),
        ([
                "id":          "xu tianchuan",
                "name":        "ÐìÌì´¨",
                "type":        "É±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/beijing/npc/xutianchuan.c",
        ]),
        ([
                "id":          "san furen",
                "name":        "×¯·òÈË",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/beijing/npc/furen.c",
        ]),
        ([
                "id":          "xuan zhen",
                "name":        "ÐþÕêµÀ³¤",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/yunlong/xuanzhen.c",
        ]),
        ([
                "id":          "xue muhua",
                "name":        "Ñ¦Ä½»ª",
                "type":        "É±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/xuemuh.c",
        ]),
        ([
                "id":          "gou du",
                "name":        "¹¶¶Á",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/goudu.c",
        ]),
        ([
                "id":          "chengzhi luohan",
                "name":        "³ÎÖ¾",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-zhi2.c",
        ]),
        ([
                "id":          "chengzhi luohan",
                "name":        "³ÎÖª",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-zhi.c",
        ]),
        ([
                "id":          "chengyu luohan",
                "name":        "³ÎÓû",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-yu.c",
        ]),
        ([
                "id":          "chengyi luohan",
                "name":        "³ÎÒâ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-yi.c",
        ]),
        ([
                "id":          "chengxing luohan",
                "name":        "³ÎÐÐ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-xing.c",
        ]),
        ([
                "id":          "chengxin luohan",
                "name":        "³ÎÐÅ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-xin2.c",
        ]),
        ([
                "id":          "chengxin luohan",
                "name":        "³ÎÐÄ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-xin.c",
        ]),
        ([
                "id":          "chengsi luohan",
                "name":        "³ÎË¼",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-si.c",
        ]),
        ([
                "id":          "chengshi luohan",
                "name":        "³ÎÊ¶",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-shi.c",
        ]),
        ([
                "id":          "chengshang luohan",
                "name":        "³ÎÉÐ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-shang.c",
        ]),
        ([
                "id":          "chengming luohan",
                "name":        "³ÎÃ÷",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-ming.c",
        ]),
        ([
                "id":          "chengmie luohan",
                "name":        "³ÎÃð",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-mie.c",
        ]),
        ([
                "id":          "chengling luohan",
                "name":        "³ÎÁé",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-ling.c",
        ]),
        ([
                "id":          "chengjing luohan",
                "name":        "³Î¾»",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-jing.c",
        ]),
        ([
                "id":          "chengjian luohan",
                "name":        "³Î¼á",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-jian.c",
        ]),
        ([
                "id":          "chengji luohan",
                "name":        "³Î¼Å",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-ji.c",
        ]),
        ([
                "id":          "chenghe luohan",
                "name":        "³ÎºÍ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-he.c",
        ]),
        ([
                "id":          "chengguan luohan",
                "name":        "³Î¹Û",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-guan.c",
        ]),
        ([
                "id":          "zhang zhiguang",
                "name":        "ÕÅÖ¾¹â",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/zhang.c",
        ]),
        ([
                "id":          "wang zhitan",
                "name":        "ÍõÖ¾Ì¹",
                "type":        "É±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/wangzhitan.c",
        ]),
        ([
                "id":          "kuai huosan",
                "name":        "¿ì»îÈý",
                "type":        "É±",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/kuai-huosan.c",
        ]),
        ([
                "id":          "jiang shangyou",
                "name":        "½­ÉÏÓÎ",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/jiang-sy.c",
        ]),
        ([
                "id":          "jingzhen shitai",
                "name":        "¾²ÕæÊ¦Ì«",
                "type":        "É±",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/emei/zhen.c",
        ]),
        ([
                "id":          "jingzhao shitai",
                "name":        "¾²ÕÕÊ¦Ì«",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/emei/zhao.c",
        ]),
        ([
                "id":          "jingxin shitai",
                "name":        "¾²ÐÄÊ¦Ì«",
                "type":        "É±",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/emei/xin.c",
        ]),
        ([
                "id":          "jingxian shitai",
                "name":        "¾²ÏÐÊ¦Ì«",
                "type":        "É±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/emei/xian.c",
        ]),
        ([
                "id":          "zhao lingzhu",
                "name":        "ÕÔÁéÖé",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/emei/ling.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "Ã½ÆÅ",
                "type":        "É±",
                "bonus":       71,
                "msg":        "",
                "object":      "/adm/npc/meipo.c",
        ]),
});
mapping query_questkh()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
