#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "mu jiang",
                "name":        "Ä¾½³",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/mujiang.c",
        ]),
        ([
                "id":          "lao xiansheng",
                "name":        "ÀÏÏÈÉú",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/laoxiansheng.c",
        ]),
        ([
                "id":          "jin xier",
                "name":        "½øÏ²¶ù",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/xier.c",
        ]),
        ([
                "id":          "xiao fan",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taishan/npc/xiao-fan.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "Ð¡É³ÃÖ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-ku.c",
        ]),
        ([
                "id":          "tong",
                "name":        "Ð¡µÀÍ¯",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/quanzhen/npc/daotong1.c",
        ]),
        ([
                "id":          "boy",
                "name":        "ÄÐº¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/boy.c",
        ]),
        ([
                "id":          "xiao lan",
                "name":        "Ð¡À¼",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guiyun/npc/xiaolan.c",
        ]),
        ([
                "id":          "heersu",
                "name":        "ºÕ¶ûËÕ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guanwai/npc/heersu.c",
        ]),
        ([
                "id":          "boy",
                "name":        "ÄÐº¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/boy.c",
        ]),
        ([
                "id":          "zhang kang",
                "name":        "ÕÅ¿µ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/foshan/npc/zhangkang.c",
        ]),
        ([
                "id":          "seller",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/emei/npc/xiao-fan.c",
        ]),
        ([
                "id":          "poor man",
                "name":        "Çîºº",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/emei/npc/poorman.c",
        ]),
        ([
                "id":          "jinxiang ke",
                "name":        "½øÏã¿Í",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/emei/npc/guest.c",
        ]),
        ([
                "id":          "dizi",
                "name":        "Å®µÜ×Ó",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/emei/npc/girldizi.c",
        ]),
        ([
                "id":          "dizi",
                "name":        "ÄÐµÜ×Ó",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/emei/npc/boydizi.c",
        ]),
        ([
                "id":          "xiao lama",
                "name":        "Ð¡À®Âï",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xueshan/npc/x_lama.c",
        ]),
        ([
                "id":          "afanti",
                "name":        "°¢·²Ìá",
                "type":        "É±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/xingxiu/npc/afanti.c",
        ]),
        ([
                "id":          "laonian sengren",
                "name":        "ÀÏÄêÉ®ÈË",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/laoniansengren.c",
        ]),
        ([
                "id":          "youke",
                "name":        "ÓÎ¿Í",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/huashan/npc/youke.c",
        ]),
        ([
                "id":          "huoji",
                "name":        "»ï¼Æ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/huanghe/npc/huoji.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/henshan/npc/xiaoer2.c",
        ]),
        ([
                "id":          "lao zhe",
                "name":        "ÀÏÕß",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/heimuya/npc/laozhe.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "ÊéÉú",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/shu-sheng.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "ÊéÉú",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/shu-sheng.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "¼Ò¶¡",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/jia.c",
        ]),
        ([
                "id":          "cui",
                "name":        "Ð¡´ä",
                "type":        "É±",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/wudang/npc/xiaocui.c",
        ]),
        ([
                "id":          "poor man",
                "name":        "Çîºº",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/poorman.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "Ò©ÆÌ»ï¼Æ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/huoji.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "Ð¡É³ÃÖ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-bei.c",
        ]),
        ([
                "id":          "girl",
                "name":        "Å®º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/quanzhou/npc/girl.c",
        ]),
        ([
                "id":          "you ke",
                "name":        "ÓÎ¿Í",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/quanzhen/npc/youke.c",
        ]),
        ([
                "id":          "dibao",
                "name":        "µØ±£",
                "type":        "É±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/hanzhong/npc/dibao.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer3.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "girl",
                "name":        "Å®º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/girl.c",
        ]),
        ([
                "id":          "cui biaotou",
                "name":        "´ÞïÚÍ·",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/fuzhou/npc/cui.c",
        ]),
        ([
                "id":          "chen apo",
                "name":        "³Â°¢ÆÅ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/chen.c",
        ]),
        ([
                "id":          "su su",
                "name":        "ËØËØ",
                "type":        "É±",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/yanziwu/npc/susu.c",
        ]),
        ([
                "id":          "alamuhan",
                "name":        "°¢À­Ä¾º±",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/xingxiu/npc/alamuhan.c",
        ]),
        ([
                "id":          "shudian laoban",
                "name":        "ÊéµêÀÏ°å",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/xiangyang/npc/shudianboss.c",
        ]),
        ([
                "id":          "shaofan shifu",
                "name":        "ÉÕ·¹Ê¦¸µ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xiangyang/npc/shaofanshifu.c",
        ]),
        ([
                "id":          "zhong ling",
                "name":        "ÖÓÁé",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/zhongling.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "Ìô·ò",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taishan/npc/tiao-fu.c",
        ]),
        ([
                "id":          "xiao hongniang",
                "name":        "Ð¡ºìÄï",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/suzhou/npc/xiao-hongniang.c",
        ]),
        ([
                "id":          "ni gu",
                "name":        "Äá¹Ã",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/nigu2.c",
        ]),
        ([
                "id":          "ni gu",
                "name":        "Äá¹Ã",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/nigu1.c",
        ]),
        ([
                "id":          "ya huan",
                "name":        "Ñ¾»·",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/lady3.c",
        ]),
        ([
                "id":          "kid",
                "name":        "Ð¡º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/kid.c",
        ]),
        ([
                "id":          "xiao fan",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-fan.c",
        ]),
        ([
                "id":          "xiang ke",
                "name":        "Ïã¿Í",
                "type":        "É±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/quanzhen/npc/xiangke.c",
        ]),
        ([
                "id":          "poor man",
                "name":        "Çîºº",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/poorman.c",
        ]),
        ([
                "id":          "cun min",
                "name":        "´åÃñ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/cunmin.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xueshan/npc/xiaoer2.c",
        ]),
        ([
                "id":          "zhuoma",
                "name":        "×¿Âê",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/xuedao/npc/zhuoma.c",
        ]),
        ([
                "id":          "girl",
                "name":        "Å®º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/girl.c",
        ]),
        ([
                "id":          "jianghu haoke",
                "name":        "½­ºþºÀ¿Í",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/haoke.c",
        ]),
        ([
                "id":          "xiao hai",
                "name":        "Ð¡º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-hai.c",
        ]),
        ([
                "id":          "shaofan seng",
                "name":        "ÉÕ·¹É®",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/shaolin/npc/shaofan-seng.c",
        ]),
        ([
                "id":          "saodi seng",
                "name":        "É¨µØÉ®",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/shaolin/npc/saodi-seng.c",
        ]),
        ([
                "id":          "seller",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/quanzhen/npc/seller.c",
        ]),
        ([
                "id":          "girl",
                "name":        "Å®º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/girl.c",
        ]),
        ([
                "id":          "tong",
                "name":        "µÀÍ¯",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/quanzhen/npc/daotong.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "¼Ò¶¡",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/meizhuang/npc/jiading.c",
        ]),
        ([
                "id":          "zhangfang",
                "name":        "ÕÊ·¿ÏÈÉú",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/lingzhou/npc/zhangfang.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao huoji",
                "name":        "Ð¡»ï¼Æ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/lingzhou/npc/daodianhuoji.c",
        ]),
        ([
                "id":          "jianghu haoke",
                "name":        "½­ºþºÀ¿Í",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/huashan/npc/haoke.c",
        ]),
        ([
                "id":          "yangzong",
                "name":        "Ñë×Ú",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/xuedao/npc/yangzong.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/xiaoer2.c",
        ]),
        ([
                "id":          "lao qiao",
                "name":        "ÇÇÈý»±",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/lao-qiao.c",
        ]),
        ([
                "id":          "da shou",
                "name":        "´òÊÖ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/shaolin/npc/da-shou.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/quanzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "kid",
                "name":        "Ð¡º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/heimuya/npc/kid.c",
        ]),
        ([
                "id":          "youke",
                "name":        "ÓÎ¿Í",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/you-ke.c",
        ]),
        ([
                "id":          "xiao ju",
                "name":        "Ð¡¾Õ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guiyun/npc/xiaoju.c",
        ]),
        ([
                "id":          "xiu cai",
                "name":        "ÂäµÚÐã²Å",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiucai.c",
        ]),
        ([
                "id":          "cun gu",
                "name":        "´å¹Ã",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/heimuya/npc/cungu.c",
        ]),
        ([
                "id":          "old woman",
                "name":        "ÀÏ´óÄï",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/oldwoman.c",
        ]),
        ([
                "id":          "lao ban",
                "name":        "¾Æ¹ÝÀÏ°å",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guanwai/npc/laoban.c",
        ]),
        ([
                "id":          "seller",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaofan.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "zhong xiaoer",
                "name":        "ÖÓÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/foshan/npc/zhongxiaoer.c",
        ]),
        ([
                "id":          "zhang chaotang",
                "name":        "ÕÅ³¯ÌÆ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/foshan/npc/zhang.c",
        ]),
        ([
                "id":          "shou shangren",
                "name":        "ÊÝÉÌÈË",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/foshan/npc/shou.c",
        ]),
        ([
                "id":          "pang shangren",
                "name":        "ÅÖÉÌÈË",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/foshan/npc/pang.c",
        ]),
        ([
                "id":          "feng qi",
                "name":        "·ïÆß",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/foshan/npc/fengqi.c",
        ]),
        ([
                "id":          "nianqing shaofu",
                "name":        "ÄêÇáÉÙ¸¾",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/emei/npc/youngwoman.c",
        ]),
        ([
                "id":          "xiao fan",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/emei/npc/xiao-fan.c",
        ]),
        ([
                "id":          "girl",
                "name":        "Î¬Îá¶ûÉÙÅ®",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xingxiu/npc/shaonv.c",
        ]),
        ([
                "id":          "poor man",
                "name":        "Çîºº",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/poorman.c",
        ]),
        ([
                "id":          "kid",
                "name":        "Ð¡º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/kid.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "¼Ò¶¡",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/jiading.c",
        ]),
        ([
                "id":          "boy",
                "name":        "ÄÐº¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/boy.c",
        ]),
        ([
                "id":          "dibao",
                "name":        "µØ±£",
                "type":        "É±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/village/npc/dibao.c",
        ]),
        ([
                "id":          "saodi seng",
                "name":        "É¨µØÉ®",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/saodiseng.c",
        ]),
        ([
                "id":          "bi nu",
                "name":        "æ¾Å®",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/suzhou/npc/lady4.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "Ð¡É³ÃÖ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-tong.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-er2.c",
        ]),
        ([
                "id":          "jingxiang ke",
                "name":        "½øÏã¿Í",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiang-ke.c",
        ]),
        ([
                "id":          "chen apo",
                "name":        "³Â°¢ÆÅ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/quanzhou/npc/chen.c",
        ]),
        ([
                "id":          "boy",
                "name":        "ÄÐº¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/quanzhou/npc/boy.c",
        ]),
        ([
                "id":          "jinxiang ke",
                "name":        "½øÏã¿Í",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xueshan/npc/xiang-ke.c",
        ]),
        ([
                "id":          "kid",
                "name":        "Ð¡º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xingxiu/npc/kid.c",
        ]),
        ([
                "id":          "jinxiang ke",
                "name":        "½øÏã¿Í",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/wudang/npc/guest.c",
        ]),
        ([
                "id":          "boy",
                "name":        "ÄÐº¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/boy.c",
        ]),
        ([
                "id":          "cha boshi",
                "name":        "²è²©Ê¿",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/henshan/npc/chaboshi.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "Ìô·ò",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/tiao-fu.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "Ð¡É³ÃÖ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/hangzhou/npc/shami.c",
        ]),
        ([
                "id":          "qianlong",
                "name":        "Ç¬Â¡»ÊµÛ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/qianlong.c",
        ]),
        ([
                "id":          "poor man",
                "name":        "Çîºº",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/poorman.c",
        ]),
        ([
                "id":          "jinxiang ke",
                "name":        "½øÏã¿Í",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/guest.c",
        ]),
        ([
                "id":          "girl",
                "name":        "Å®º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/girl.c",
        ]),
        ([
                "id":          "girl",
                "name":        "²É²èÅ®",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/caichanu.c",
        ]),
        ([
                "id":          "boy",
                "name":        "ÄÐº¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/boy.c",
        ]),
        ([
                "id":          "xiao lama",
                "name":        "Ð¡À®Âï",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xuedao/npc/x_lama.c",
        ]),
        ([
                "id":          "caiyao ren",
                "name":        "²ÉÒ©ÈË",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xuedao/npc/caiyaoren.c",
        ]),
        ([
                "id":          "old woman",
                "name":        "ÀÏ´óÄï",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/oldwoman.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taishan/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "qiao fu",
                "name":        "éÔ·ò",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/huanghe/npc/qiaofu.c",
        ]),
        ([
                "id":          "liu furen",
                "name":        "Áõ·òÈË",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/henshan/npc/liufuren.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "pihuo shang",
                "name":        "Æ¤»õÉÌ",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/guanwai/npc/pihuoshang.c",
        ]),
        ([
                "id":          "xiao lama",
                "name":        "Ð¡À®Âï",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xueshan/npc/x_lama1.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "ïÚÍ·",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/xiangyang/npc/biaotou.c",
        ]),
        ([
                "id":          "girl",
                "name":        "Å®º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/girl.c",
        ]),
        ([
                "id":          "bi nu",
                "name":        "æ¾Å®",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taohua/npc/binu.c",
        ]),
        ([
                "id":          "seller",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/seller.c",
        ]),
        ([
                "id":          "girl",
                "name":        "ËÕÖÝÅ®º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/lady1.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "Ð¡É³ÃÖ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-nan.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-er.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "Ð¡É³ÃÖ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-ci.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "Ìô·ò",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/tiao-fu.c",
        ]),
        ([
                "id":          "seng bing",
                "name":        "»¤ÁÖÉ®±ø",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/shaolin/npc/seng-bing1.c",
        ]),
        ([
                "id":          "kid",
                "name":        "Ð¡º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/kid.c",
        ]),
        ([
                "id":          "jieyin shi",
                "name":        "½ÓÒýÊ¹",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/mingjiao/npc/jieyinshi.c",
        ]),
        ([
                "id":          "woman",
                "name":        "Î¬Îá¶û×å¸¾Å®",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xingxiu/npc/woman.c",
        ]),
        ([
                "id":          "muyang ren",
                "name":        "ÄÁÑòÈË",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xingxiu/npc/herdsman.c",
        ]),
        ([
                "id":          "caiyao ren",
                "name":        "²ÉÒ©ÈË",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xingxiu/npc/caiyaoren.c",
        ]),
        ([
                "id":          "wang yuyan",
                "name":        "ÍõÓïæÌ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xiaoyao/npc/wangyuyan.c",
        ]),
        ([
                "id":          "lai fuer",
                "name":        "À´¸£¶ù",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/fuer.c",
        ]),
        ([
                "id":          "seller",
                "name":        "Ð¡··",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/seller.c",
        ]),
        ([
                "id":          "kid",
                "name":        "Ð¡º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/kid.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "ÊéÉú",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taishan/npc/shu-sheng.c",
        ]),
        ([
                "id":          "girl",
                "name":        "ËÕÖÝÉÙÅ®",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/lady2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/xiaoer1.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/xiaoer.c",
        ]),
        ([
                "id":          "chu shi",
                "name":        "³øÊ¦",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/meizhuang/npc/chushi.c",
        ]),
        ([
                "id":          "xiao shimei",
                "name":        "Ð¡Ê¦ÃÃ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/huashan/npc/girldizi.c",
        ]),
        ([
                "id":          "youke",
                "name":        "ÓÎ¿Í",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/youke.c",
        ]),
        ([
                "id":          "yangcan nu",
                "name":        "Ñø²ÏÅ®",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/yangcannu.c",
        ]),
        ([
                "id":          "xue laoban",
                "name":        "Ñ¦ÀÏ°å",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/xueboss.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao daogu",
                "name":        "Ð¡µÀ¹Ã",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/dali/npc/xiaodaogu.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "ÎÚÒÄÉÌ··",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/wshangfan.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "Ì¨ÒÄÉÌ··",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/tshangfan.c",
        ]),
        ([
                "id":          "tai jian",
                "name":        "Ì«¼à",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/taijian.c",
        ]),
        ([
                "id":          "shi jiang",
                "name":        "Ê¯½³",
                "type":        "É±",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/shijiang.c",
        ]),
        ([
                "id":          "pihuo shang",
                "name":        "Æ¤»õÉÌ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/pihuoshang.c",
        ]),
        ([
                "id":          "pei cong",
                "name":        "Åã´Ó",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/peicong.c",
        ]),
        ([
                "id":          "oldman",
                "name":        "°ÚÒÄÀÏÛÅ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/oldman.c",
        ]),
        ([
                "id":          "nong fu",
                "name":        "Å©·ò",
                "type":        "É±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/dali/npc/nongfu2.c",
        ]),
        ([
                "id":          "nong fu",
                "name":        "Ì¨ÒÄÅ©¸¾",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/nongfu1.c",
        ]),
        ([
                "id":          "nong fu",
                "name":        "Å©·ò",
                "type":        "É±",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/nongfu.c",
        ]),
        ([
                "id":          "muyang ren",
                "name":        "ÄÁÑòÈË",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/muyangren.c",
        ]),
        ([
                "id":          "muyang nv",
                "name":        "ÄÁÑòÅ®",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/muyangnu.c",
        ]),
        ([
                "id":          "lao jisi",
                "name":        "ÎÚÒÄÀÏ¼ÀË¾",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/laojisi.c",
        ]),
        ([
                "id":          "kid",
                "name":        "°ÚÒÄÐ¡º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/kid.c",
        ]),
        ([
                "id":          "kanzhu ren",
                "name":        "¿³ÖñÈË",
                "type":        "É±",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/kanzhuren.c",
        ]),
        ([
                "id":          "guan jia",
                "name":        "¹Ü¼Ò",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/guanjia.c",
        ]),
        ([
                "id":          "girl",
                "name":        "ÄÏ¹ú¹ÃÄï",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/dali/npc/girl1.c",
        ]),
        ([
                "id":          "ge nu",
                "name":        "¸èÅ®",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/genu.c",
        ]),
        ([
                "id":          "fu nu",
                "name":        "Ì¨ÒÄ¸¾Å®",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/funu.c",
        ]),
        ([
                "id":          "fangsha nu",
                "name":        "·ÄÉ´Å®",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/dali/npc/fangshanu.c",
        ]),
        ([
                "id":          "cun fu",
                "name":        "´å¸¾",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/cunfu.c",
        ]),
        ([
                "id":          "caisun ren",
                "name":        "²ÉËñÈË",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/caisunren1.c",
        ]),
        ([
                "id":          "caisun ren",
                "name":        "²ÉËñÈË",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/caisunren.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "Ì¨ÒÄÉÌ··",
                "type":        "É±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/dali/npc/bshangfan.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "¡¸Æ½Í¨ïÚ¾Ö¡¹ïÚÍ·",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/biaotou.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/chengdu/npc/xiaoer2.c",
        ]),
        ([
                "id":          "yaodian huoji",
                "name":        "Ò©µê»ï¼Æ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/chengdu/npc/huoji.c",
        ]),
        ([
                "id":          "xiao guizi",
                "name":        "Ð¡¹ð×Ó",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/xiaoguiz.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/xiaoer.c",
        ]),
        ([
                "id":          "li apo",
                "name":        "Àî°¢ÆÅ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/liapo.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "Ò©ÆÌ»ï¼Æ",
                "type":        "É±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/city/npc/huoji2.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "Ò©ÆÌ»ï¼Æ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/huoji.c",
        ]),
        ([
                "id":          "hong niang",
                "name":        "ºìÄï",
                "type":        "É±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/city/npc/hongniang.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "ïÚÍ·",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/city/npc/biaotou.c",
        ]),
        ([
                "id":          "aqing sao",
                "name":        "°¢ÇìÉ©",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/aqingsao.c",
        ]),
        ([
                "id":          "zi yi",
                "name":        "[35m×ÏÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/ziyi.c",
        ]),
        ([
                "id":          "yahuan",
                "name":        "Ñ¾»·",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/yahuan.c",
        ]),
        ([
                "id":          "xiaoer",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiaoer",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/changan/npc/xiaoer.c",
        ]),
        ([
                "id":          "waiter",
                "name":        "²è¹ÝÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/teawaiter.c",
        ]),
        ([
                "id":          "ru hua",
                "name":        "Èç»¨",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/ruhua.c",
        ]),
        ([
                "id":          "qing yi",
                "name":        "[1;36mÇàÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/qingyi.c",
        ]),
        ([
                "id":          "lv yi",
                "name":        "[1;32mÂÌÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/luyi.c",
        ]),
        ([
                "id":          "lan yi",
                "name":        "[1;34mÀ¶ÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/lanyi.c",
        ]),
        ([
                "id":          "zhang lanxiang",
                "name":        "ÕÅÀ¼Ïã",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/lanxiang.c",
        ]),
        ([
                "id":          "ji nu",
                "name":        "¼ËÅ®",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/jinu.c",
        ]),
        ([
                "id":          "huang yi",
                "name":        "[1;33m»ÆÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/huangyi.c",
        ]),
        ([
                "id":          "hong yi",
                "name":        "[1;31mºìÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/hongyi.c",
        ]),
        ([
                "id":          "maihua guniang",
                "name":        "Âô»¨¹ÃÄï",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/girl.c",
        ]),
        ([
                "id":          "fen yi",
                "name":        "[1;35m·ÛÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/fenyi.c",
        ]),
        ([
                "id":          "shi jiugong",
                "name":        "Ê±¾Å¹«",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/doctor.c",
        ]),
        ([
                "id":          "bai yi",
                "name":        "[1;37m°×ÒÂ[2;37;0m",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/baiyi.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/beijing/npc/xiaoer.c",
        ]),
        ([
                "id":          "flower girl",
                "name":        "Âô»¨¹ÃÄï",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/beijing/npc/flowerg.c",
        ]),
        ([
                "id":          "zhang ma",
                "name":        "ÕÅÂè",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/zhangma.c",
        ]),
        ([
                "id":          "ya huan",
                "name":        "Ñ¾»·",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/yahuan.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "µêÐ¡¶þ",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/xiaoer.c",
        ]),
        ([
                "id":          "woman",
                "name":        "Å©¼Ò¸¾Å®",
                "type":        "É±",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/baituo/npc/woman.c",
        ]),
        ([
                "id":          "qiao fu",
                "name":        "éÔ·ò",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/qiaofu.c",
        ]),
        ([
                "id":          "man",
                "name":        "Å©Ãñ",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/baituo/npc/man.c",
        ]),
        ([
                "id":          "kid",
                "name":        "Ð¡º¢",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/kid.c",
        ]),
        ([
                "id":          "jin hua",
                "name":        "½ð»¨",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/jinhua.c",
        ]),
        ([
                "id":          "cun gu",
                "name":        "´å¹Ã",
                "type":        "É±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/baituo/npc/cungu.c",
        ]),
        ([
                "id":          "qing feng",
                "name":        "Çå·ç",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/wudang/qingfeng.c",
        ]),
        ([
                "id":          "ming yue",
                "name":        "Ã÷ÔÂ",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/wudang/mingyue.c",
        ]),
        ([
                "id":          "daotong",
                "name":        "µÀÍ¯",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/wudang/daotong.c",
        ]),
        ([
                "id":          "xu tong",
                "name":        "ÐéÍ¨",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xu-tong.c",
        ]),
        ([
                "id":          "qingyuan biqiu",
                "name":        "ÇåÔµ±ÈÇð",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-yuan.c",
        ]),
        ([
                "id":          "qingxiao biqiu",
                "name":        "ÇåÏþ±ÈÇð",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-xiao.c",
        ]),
        ([
                "id":          "qingwu biqiu",
                "name":        "ÇåÎÞ±ÈÇð",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wu.c",
        ]),
        ([
                "id":          "qingwen biqiu",
                "name":        "ÇåÎÅ±ÈÇð",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wen.c",
        ]),
        ([
                "id":          "qingwei biqiu",
                "name":        "ÇåÎª±ÈÇð",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wei.c",
        ]),
        ([
                "id":          "qingshan biqiu",
                "name":        "ÇåÉÆ±ÈÇð",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-shan.c",
        ]),
        ([
                "id":          "qingle biqiu",
                "name":        "ÇåÀÖ±ÈÇð",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-le.c",
        ]),
        ([
                "id":          "qingguan biqiu",
                "name":        "Çå¹Û±ÈÇð",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-guan.c",
        ]),
        ([
                "id":          "qingfa biqiu",
                "name":        "Çå·¨±ÈÇð",
                "type":        "É±",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-fa.c",
        ]),
        ([
                "id":          "zhao gouer",
                "name":        "ÕÔ¹·¶ù",
                "type":        "É±",
                "bonus":       65,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/zhao-gouer.c",
        ]),
        ([
                "id":          "wenyin",
                "name":        "ÎÄÒôÐ¡Ê¦Ì«",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/wenyin.c",
        ]),
        ([
                "id":          "wenqing",
                "name":        "ÎÄÇåÐ¡Ê¦Ì«",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/wenqing.c",
        ]),
        ([
                "id":          "wenhui",
                "name":        "ÎÄêÍÐ¡Ê¦Ì«",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/wenhui.c",
        ]),
        ([
                "id":          "wenfang",
                "name":        "ÎÄ·½Ð¡Ê¦Ì«",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/wenfang.c",
        ]),
        ([
                "id":          "daoming",
                "name":        "µÀÃ÷Ð¡Ê¦¸¸",
                "type":        "É±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/daoming.c",
        ]),
        ([
                "id":          "hong niang",
                "name":        "ºìÄï",
                "type":        "É±",
                "bonus":       50,
                "msg":        "",
                "object":      "/adm/npc/hongniang.c",
        ]),
});
mapping query_questkh()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
