#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "yu zu",
                "name":        "”¸◊‰",
                "type":        "…±",
                "bonus":       110,
                "msg":        "",
                "object":      "/d/shaolin/npc/yu-zu.c",
        ]),
        ([
                "id":          "lin pingzhi",
                "name":        "¡÷∆Ω÷Æ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/lin-pingzhi.c",
        ]),
        ([
                "id":          "yu canghai",
                "name":        "”‡≤◊∫£",
                "type":        "…±",
                "bonus":       66,
                "msg":        "",
                "object":      "/kungfu/class/qingcheng/yu.c",
        ]),
        ([
                "id":          "feng xifan",
                "name":        "∑ÎŒ˝∑∂",
                "type":        "…±",
                "bonus":       106,
                "msg":        "",
                "object":      "/d/guanwai/npc/fengxifan.c",
        ]),
        ([
                "id":          "zhao banshan",
                "name":        "’‘∞Î…Ω",
                "type":        "…±",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/zhao.c",
        ]),
        ([
                "id":          "wuchen daozhang",
                "name":        "Œﬁ≥æµ¿≥§",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/wuchen.c",
        ]),
        ([
                "id":          "zhang chengyun",
                "name":        "’≈≥À‘∆",
                "type":        "…±",
                "bonus":       106,
                "msg":        "",
                "object":      "/d/heimuya/npc/zhang2.c",
        ]),
        ([
                "id":          "zhao he",
                "name":        "’‘∫◊",
                "type":        "…±",
                "bonus":       106,
                "msg":        "",
                "object":      "/d/heimuya/npc/zhaohe.c",
        ]),
        ([
                "id":          "fan song",
                "name":        "∑∂À…",
                "type":        "…±",
                "bonus":       106,
                "msg":        "",
                "object":      "/d/heimuya/npc/fansong.c",
        ]),
        ([
                "id":          "cong buqi",
                "name":        "¥‘≤ª∆˙",
                "type":        "…±",
                "bonus":       73,
                "msg":        "",
                "object":      "/kungfu/class/huashan/cong-buqi.c",
        ]),
        ([
                "id":          "cheng buyou",
                "name":        "≥…≤ª”«",
                "type":        "…±",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/huashan/cheng-buyou.c",
        ]),
        ([
                "id":          "taoshi xian",
                "name":        "Ã“ µœ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao6.c",
        ]),
        ([
                "id":          "taohua xian",
                "name":        "Ã“ª®œ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao5.c",
        ]),
        ([
                "id":          "taoye xian",
                "name":        "Ã““∂œ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao4.c",
        ]),
        ([
                "id":          "taozhi xian",
                "name":        "Ã“÷¶œ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao3.c",
        ]),
        ([
                "id":          "taogan xian",
                "name":        "Ã“∏…œ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao2.c",
        ]),
        ([
                "id":          "taogen xian",
                "name":        "Ã“∏˘œ…",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao1.c",
        ]),
        ([
                "id":          "qu lingfeng",
                "name":        "«˙»˝",
                "type":        "…±",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/taohua/qu.c",
        ]),
        ([
                "id":          "xu xueting",
                "name":        "–Ì—©Õ§",
                "type":        "…±",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shenlong/xu.c",
        ]),
        ([
                "id":          "peng youjing",
                "name":        "≈Ì”–æ¥",
                "type":        "…±",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/peng.c",
        ]),
        ([
                "id":          "liang zhanglao",
                "name":        "¡∫≥§¿œ",
                "type":        "…±",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/liang.c",
        ]),
        ([
                "id":          "jian zhanglao",
                "name":        "ºÚ≥§¿œ",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/jian.c",
        ]),
        ([
                "id":          "duan yu",
                "name":        "∂Œ”˛",
                "type":        "…±",
                "bonus":       106,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyu.c",
        ]),
        ([
                "id":          "xiang wentian",
                "name":        "œÚŒ ÃÏ",
                "type":        "…±",
                "bonus":       85,
                "msg":        "",
                "object":      "/d/heimuya/npc/xiang.c",
        ]),
        ([
                "id":          "miao renfeng",
                "name":        "√Á»À∑Ô",
                "type":        "…±",
                "bonus":       82,
                "msg":        "",
                "object":      "/d/shaolin/npc/miao.c",
        ]),
        ([
                "id":          "ren woxing",
                "name":        "»ŒŒ“––",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/heimuya/npc/renwoxing.c",
        ]),
        ([
                "id":          "zuo lengchan",
                "name":        "◊Û¿‰Ï¯",
                "type":        "…±",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/songshan/zuo.c",
        ]),
        ([
                "id":          "feng xifan",
                "name":        "∑ÎŒ˝∑∂",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/guanwai/npc/fengxifan.c",
        ]),
        ([
                "id":          "wen cangsong",
                "name":        "Œ≈≤‘À…",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/wensong.c",
        ]),
        ([
                "id":          "zhang chengyun",
                "name":        "’≈≥À‘∆",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/heimuya/npc/zhang2.c",
        ]),
        ([
                "id":          "zhao he",
                "name":        "’‘∫◊",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/heimuya/npc/zhaohe.c",
        ]),
        ([
                "id":          "yue nv",
                "name":        "‘Ω≈Æ",
                "type":        "…±",
                "bonus":       85,
                "msg":        "",
                "object":      "/d/hangzhou/npc/yuenv.c",
        ]),
        ([
                "id":          "fan song",
                "name":        "∑∂À…",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/heimuya/npc/fansong.c",
        ]),
        ([
                "id":          "murong fu",
                "name":        "ƒΩ»›∏¥",
                "type":        "…±",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/murong/murongfu.c",
        ]),
        ([
                "id":          "murong longcheng",
                "name":        "ƒΩ»›¡˙≥«",
                "type":        "…±",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/murong/longcheng.c",
        ]),
        ([
                "id":          "zhuo bufan",
                "name":        "◊ø≤ª∑≤",
                "type":        "…±",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/zhuo.c",
        ]),
        ([
                "id":          "hu yizhi",
                "name":        "∫˙“›÷Æ",
                "type":        "…±",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/hu/huyizhi.c",
        ]),
        ([
                "id":          "yang guo",
                "name":        "—Óπ˝",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/gumu/yang.c",
        ]),
        ([
                "id":          "jinlun fawang",
                "name":        "Ω¬÷∑®Õı",
                "type":        "…±",
                "bonus":       84,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/fawang.c",
        ]),
        ([
                "id":          "hong antong",
                "name":        "∫È∞≤Õ®",
                "type":        "…±",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/shenlong/hong.c",
        ]),
        ([
                "id":          "du nan",
                "name":        "∂…ƒ—",
                "type":        "…±",
                "bonus":       85,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-nan.c",
        ]),
        ([
                "id":          "du jie",
                "name":        "∂…ΩŸ",
                "type":        "…±",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-jie.c",
        ]),
        ([
                "id":          "du e",
                "name":        "∂…∂Ú",
                "type":        "…±",
                "bonus":       84,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-e.c",
        ]),
        ([
                "id":          "lin chaoying",
                "name":        "¡÷≥Ø”¢",
                "type":        "…±",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/gumu/lin.c",
        ]),
        ([
                "id":          "duan yu",
                "name":        "∂Œ”˛",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyu.c",
        ]),
        ([
                "id":          "duan yanqing",
                "name":        "∂Œ—”«Ï",
                "type":        "…±",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyq.c",
        ]),
        ([
                "id":          "shanzei tou",
                "name":        "…Ω‘ÙÕ∑",
                "type":        "…±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/baituo/npc/shanzei3.c",
        ]),
        ([
                "id":          "jiuyi daoren",
                "name":        "æ≈“Ìµ¿»À",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/lingjiu/npc/jiuyi.c",
        ]),
        ([
                "id":          "wu santong",
                "name":        "Œ‰»˝Õ®",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wusantong.c",
        ]),
        ([
                "id":          "wang bashuai",
                "name":        "Õı∞ÀÀ•",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/wang8.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "√Ω∆≈",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/suzhou/npc/meipo.c",
        ]),
        ([
                "id":          "sha tianjiang",
                "name":        "…≥ÃÏΩ≠",
                "type":        "…±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/songshan/npc/sha.c",
        ]),
        ([
                "id":          "yue lingshan",
                "name":        "‘¿¡È…∫",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huashan/npc/yue-lingshan.c",
        ]),
        ([
                "id":          "hou tonghai",
                "name":        "∫ÓÕ®∫£",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huanghe/npc/hou.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "∞◊“¬Œ‰ ø",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi1.c",
        ]),
        ([
                "id":          "di xiu",
                "name":        "µ“–ﬁ",
                "type":        "…±",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/songshan/di.c",
        ]),
        ([
                "id":          "yu renhao",
                "name":        "”⁄»À∫¿",
                "type":        "…±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/yu.c",
        ]),
        ([
                "id":          "san hu",
                "name":        "∫ˆ¬◊»˝ª¢",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sanhu.c",
        ]),
        ([
                "id":          "jiao wenqi",
                "name":        "ΩπŒƒ∆⁄",
                "type":        "…±",
                "bonus":       99,
                "msg":        "",
                "object":      "/d/guanwai/npc/jiaowenqi.c",
        ]),
        ([
                "id":          "zu qianqiu",
                "name":        "◊Ê«ß«Ô",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huanghe/npc/zu.c",
        ]),
        ([
                "id":          "er hu",
                "name":        "∫ˆ¬◊∂˛ª¢",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/erhu.c",
        ]),
        ([
                "id":          "da hu",
                "name":        "∫ˆ¬◊¥Ûª¢",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/dahu.c",
        ]),
        ([
                "id":          "bo chen",
                "name":        "≤∑≥¡",
                "type":        "…±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/songshan/npc/bo.c",
        ]),
        ([
                "id":          "lao denuo",
                "name":        "¿Õµ¬≈µ",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/huashan/npc/lao-denuo.c",
        ]),
        ([
                "id":          "sun popo",
                "name":        "ÀÔ∆≈∆≈",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/gumu/npc/sun.c",
        ]),
        ([
                "id":          "hong renxiong",
                "name":        "∫È»À–€",
                "type":        "…±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/hong.c",
        ]),
        ([
                "id":          "song qingshu",
                "name":        "ÀŒ«‡ È",
                "type":        "…±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/emei/npc/songqingshu.c",
        ]),
        ([
                "id":          "wu xiuwen",
                "name":        "Œ‰–ﬁŒƒ",
                "type":        "…±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wuxiuwen.c",
        ]),
        ([
                "id":          "zhou wushu",
                "name":        "÷‹ŒÂ ‰",
                "type":        "…±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhou5.c",
        ]),
        ([
                "id":          "zheng qimie",
                "name":        "÷£∆ﬂ√",
                "type":        "…±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zheng7.c",
        ]),
        ([
                "id":          "lu bai",
                "name":        "¬Ω∞ÿ",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/songshan/npc/lu.c",
        ]),
        ([
                "id":          "gao kexin",
                "name":        "∏ﬂøÀ–¬",
                "type":        "…±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/songshan/npc/gao.c",
        ]),
        ([
                "id":          "sun sanhui",
                "name":        "ÀÔ»˝ªŸ",
                "type":        "…±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/sun3.c",
        ]),
        ([
                "id":          "yuji zi",
                "name":        "”ÒÁ·◊”",
                "type":        "…±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yujizi.c",
        ]),
        ([
                "id":          "zhong zhen",
                "name":        "÷”’Ú",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/songshan/npc/zhong.c",
        ]),
        ([
                "id":          "luo renjie",
                "name":        "¬ﬁ»ÀΩ‹",
                "type":        "…±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/luo.c",
        ]),
        ([
                "id":          "zhu ziliu",
                "name":        "÷Ï◊”¡¯",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/zhuziliu.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "∫Ï“¬Œ‰ ø",
                "type":        "…±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi2.c",
        ]),
        ([
                "id":          "li kexiu",
                "name":        "¿Óø…–„",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/hangzhou/npc/likexiu.c",
        ]),
        ([
                "id":          "si hu",
                "name":        "∫ˆ¬◊Àƒª¢",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sihu.c",
        ]),
        ([
                "id":          "yuqing zi",
                "name":        "”ÒÌ‡◊”",
                "type":        "…±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yuqingzi.c",
        ]),
        ([
                "id":          "ding mian",
                "name":        "∂°√„",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/songshan/npc/ding.c",
        ]),
        ([
                "id":          "huo renying",
                "name":        "∫Ó»À”¢",
                "type":        "…±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/hou.c",
        ]),
        ([
                "id":          "hu qingniu",
                "name":        "∫˙«‡≈£",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/mingjiao/npc/hu.c",
        ]),
        ([
                "id":          "li si",
                "name":        "¿ÓÀƒ",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/village/npc/xiejian.c",
        ]),
        ([
                "id":          "zhao yishang",
                "name":        "’‘“ª…À",
                "type":        "…±",
                "bonus":       62,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhao1.c",
        ]),
        ([
                "id":          "li sicui",
                "name":        "¿ÓÀƒ¥›",
                "type":        "…±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/li4.c",
        ]),
        ([
                "id":          "yuyin zi",
                "name":        "”Ò“Ù◊”",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yuyinzi.c",
        ]),
        ([
                "id":          "tang yinghu",
                "name":        "Ã¿”¢¿",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/songshan/npc/tang.c",
        ]),
        ([
                "id":          "ping si",
                "name":        "∆ΩÀƒ",
                "type":        "…±",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/hu/pingsi.c",
        ]),
        ([
                "id":          "huo xiansheng",
                "name":        "ªÙœ»…˙",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/dali/npc/huo.c",
        ]),
        ([
                "id":          "yulin jun",
                "name":        "”˘¡÷æ¸",
                "type":        "…±",
                "bonus":       95,
                "msg":        "",
                "object":      "/d/changan/npc/yulinjun.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "Œ‰Ω´",
                "type":        "…±",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/wujiang.c",
        ]),
        ([
                "id":          "murong hao",
                "name":        "ƒΩ»›∫¿",
                "type":        "…±",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/changan/npc/murong-hao.c",
        ]),
        ([
                "id":          "da shou",
                "name":        "¥Ú ÷",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/dashou.c",
        ]),
        ([
                "id":          "bao biao",
                "name":        "»∫”Ò¬•±£Ô⁄",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/baobiao.c",
        ]),
        ([
                "id":          "gongtangcang guoshi",
                "name":        "π±Ã∆≤÷π˙ ¶",
                "type":        "…±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/guoshi.c",
        ]),
        ([
                "id":          "shan yong",
                "name":        "…∆”¬",
                "type":        "…±",
                "bonus":       61,
                "msg":        "",
                "object":      "/kungfu/class/xuedao/shanyong.c",
        ]),
        ([
                "id":          "xue muhua",
                "name":        "—¶ƒΩª™",
                "type":        "…±",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/xuemuh.c",
        ]),
        ([
                "id":          "zhao zhijing",
                "name":        "’‘÷ææ¥",
                "type":        "…±",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/zhao.c",
        ]),
        ([
                "id":          "kuai huosan",
                "name":        "øÏªÓ»˝",
                "type":        "…±",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/kuai-huosan.c",
        ]),
        ([
                "id":          "jiang shangyou",
                "name":        "Ω≠…œ”Œ",
                "type":        "…±",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/jiang-sy.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "√Ω∆≈",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/adm/npc/meipo.c",
        ]),
});
mapping query_questsn()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
