#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "zhao yishang",
                "name":        "’‘“ª…À",
                "type":        "…±",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/zhao1.c",
        ]),
        ([
                "id":          "sun sanhui",
                "name":        "ÀÔ»˝ªŸ",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/sun3.c",
        ]),
        ([
                "id":          "li sicui",
                "name":        "¿ÓÀƒ¥›",
                "type":        "…±",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/li4.c",
        ]),
        ([
                "id":          "zhang san",
                "name":        "’≈»˝",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/wudang/npc/baibian.c",
        ]),
        ([
                "id":          "jiang baisheng",
                "name":        "Ω≠∞Ÿ §",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/taishan/npc/jiang.c",
        ]),
        ([
                "id":          "yafu",
                "name":        "—∆∏æ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hengshan/npc/yafu.c",
        ]),
        ([
                "id":          "little monkey",
                "name":        "–°∫Ô",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/little_monkey.c",
        ]),
        ([
                "id":          "ha dani",
                "name":        "π˛¥Ôƒ·",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/guanwai/npc/hadani.c",
        ]),
        ([
                "id":          "dongbei hu",
                "name":        "∂´±±ª¢",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guanwai/npc/dongbeihu.c",
        ]),
        ([
                "id":          "diao",
                "name":        "[1;33mΩµÒ[2;37;0m",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/guanwai/npc/diao.c",
        ]),
        ([
                "id":          "hei xiong",
                "name":        "[36m∫⁄–‹[2;37;0m",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guanwai/npc/bear.c",
        ]),
        ([
                "id":          "huanan hu",
                "name":        "ª™ƒœª¢",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/yanping/npc/huananhu.c",
        ]),
        ([
                "id":          "wu liupo",
                "name":        "Œ‚¡˘∆∆",
                "type":        "…±",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/wu6.c",
        ]),
        ([
                "id":          "heiyi ren",
                "name":        "∫⁄“¬»À",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/heimuya/npc/heiyiren.c",
        ]),
        ([
                "id":          "young girl",
                "name":        "ƒÍ«·≈Æµ‹◊”",
                "type":        "…±",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/shenlong/npc/girl.c",
        ]),
        ([
                "id":          "yu renyan",
                "name":        "”‡»À—Â",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/qingcheng/npc/yuyan.c",
        ]),
        ([
                "id":          "jia renda",
                "name":        "º÷»À¥Ô",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/qingcheng/npc/jia.c",
        ]),
        ([
                "id":          "wu liupo",
                "name":        "Œ‚¡˘∆∆",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/wu6.c",
        ]),
        ([
                "id":          "laohu",
                "name":        "¿œª¢",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/wudang/npc/laohu.c",
        ]),
        ([
                "id":          "zhen youqing",
                "name":        "’Á”–«Ï",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/suzhou/npc/shiye.c",
        ]),
        ([
                "id":          "zhang laosan",
                "name":        "’¬¿œ»˝",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/shenlong/npc/zhang3.c",
        ]),
        ([
                "id":          "mu jianping",
                "name":        "„ÂΩ£∆¡",
                "type":        "…±",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/shenlong/npc/mujianping.c",
        ]),
        ([
                "id":          "horse",
                "name":        "[1;36m«‡Êı¬Ì[2;37;0m",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/obj/horse.c",
        ]),
        ([
                "id":          "wanyan honglie",
                "name":        "ÕÍ—’∫È¡“",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/guiyun/npc/wanyanhonglie.c",
        ]),
        ([
                "id":          "qiu qianzhang",
                "name":        "Ù√«ß’…",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guiyun/npc/qiuqianzhang.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "«‡“¬Œ‰ ø",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi3.c",
        ]),
        ([
                "id":          "shen renjun",
                "name":        "…Í»Àø°",
                "type":        "…±",
                "bonus":       96,
                "msg":        "",
                "object":      "/d/qingcheng/npc/shen.c",
        ]),
        ([
                "id":          "yan ji",
                "name":        "—÷ª˘",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/guanwai/npc/yanji.c",
        ]),
        ([
                "id":          "wolf",
                "name":        "[37m“∞¿«[2;37;0m",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/clone/quarry/lang2.c",
        ]),
        ([
                "id":          "feng yiming",
                "name":        "∑Ô“ª√˘",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/foshan/npc/fengyiming.c",
        ]),
        ([
                "id":          "cow",
                "name":        "[1;37m¥Ûª∆≈£[2;37;0m",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/wudang/npc/cow.c",
        ]),
        ([
                "id":          "qian erbai",
                "name":        "«Æ∂˛∞‹",
                "type":        "…±",
                "bonus":       83,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/qian2.c",
        ]),
        ([
                "id":          "sun baopi",
                "name":        "ÀÔ∞˛∆§",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/suzhou/npc/sun.c",
        ]),
        ([
                "id":          "gongzi",
                "name":        "π´◊”∏Á",
                "type":        "…±",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/suzhou/npc/gongzi.c",
        ]),
        ([
                "id":          "feng zhengdong",
                "name":        "∑Î’˝∂´",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/suzhou/npc/feng.c",
        ]),
        ([
                "id":          "fang yi",
                "name":        "∑Ω‚˘",
                "type":        "…±",
                "bonus":       62,
                "msg":        "",
                "object":      "/d/shenlong/npc/fangyi.c",
        ]),
        ([
                "id":          "young boy",
                "name":        "ƒÍ«·µ‹◊”",
                "type":        "…±",
                "bonus":       58,
                "msg":        "",
                "object":      "/d/shenlong/npc/boy4.c",
        ]),
        ([
                "id":          "old man",
                "name":        "¿œ’ﬂ",
                "type":        "…±",
                "bonus":       81,
                "msg":        "",
                "object":      "/d/shenlong/npc/old.c",
        ]),
        ([
                "id":          "fang renzhi",
                "name":        "∑Ω»À÷«",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/qingcheng/npc/fang.c",
        ]),
        ([
                "id":          "zheng qimie",
                "name":        "÷£∆ﬂ√",
                "type":        "…±",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/zheng7.c",
        ]),
        ([
                "id":          "wang bashuai",
                "name":        "Õı∞ÀÀ•",
                "type":        "…±",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/wang8.c",
        ]),
        ([
                "id":          "laohu",
                "name":        "¿œª¢",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/hangzhou/npc/laohu.c",
        ]),
        ([
                "id":          "zhong wanchou",
                "name":        "÷”ÕÚ≥",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/zhong.c",
        ]),
        ([
                "id":          "zhou wushu",
                "name":        "÷‹ŒÂ ‰",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/zhou5.c",
        ]),
        ([
                "id":          "yang lianting",
                "name":        "—Ó¡´Õ§",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/heimuya/npc/yang.c",
        ]),
        ([
                "id":          "guo fu",
                "name":        "π˘‹Ω",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/guofu.c",
        ]),
        ([
                "id":          "gan baobao",
                "name":        "∏ ±¶±¶",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/gan.c",
        ]),
        ([
                "id":          "wan daping",
                "name":        "ÕÚ¥Û∆Ω",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/songshan/npc/wan.c",
        ]),
        ([
                "id":          "qian erbai",
                "name":        "«Æ∂˛∞‹",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/mingjiao/yuan/qian2.c",
        ]),
        ([
                "id":          "ma zei",
                "name":        "¬Ì‘Ù",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huanghe/npc/mazei.c",
        ]),
        ([
                "id":          "ouyang ke",
                "name":        "≈∑—ÙøÀ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/ouyang/ouyangke.c",
        ]),
        ([
                "id":          "caihua zi",
                "name":        "≤…ª®◊”",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xingxiu/npc/caihua.c",
        ]),
        ([
                "id":          "shi dengda",
                "name":        " ∑µ«¥Ô",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/songshan/npc/shi.c",
        ]),
        ([
                "id":          "young boy",
                "name":        "ƒÍ«·µ‹◊”",
                "type":        "…±",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/shenlong/npc/boy3.c",
        ]),
        ([
                "id":          "young boy",
                "name":        "ƒÍ«·µ‹◊”",
                "type":        "…±",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/shenlong/npc/boy.c",
        ]),
        ([
                "id":          "ji rentong",
                "name":        "º™»ÀÕ®",
                "type":        "…±",
                "bonus":       96,
                "msg":        "",
                "object":      "/d/qingcheng/npc/ji.c",
        ]),
        ([
                "id":          "shan yang",
                "name":        "…Ω—Ú",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/dali/npc/shanyang.c",
        ]),
        ([
                "id":          "laohu",
                "name":        "¿œª¢",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/dali/npc/laohu.c",
        ]),
        ([
                "id":          "jianghu yiren",
                "name":        "Ω≠∫˛“’»À",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/jianghuyiren.c",
        ]),
        ([
                "id":          "he hongyao",
                "name":        "∫Œ∫Ï“©",
                "type":        "…±",
                "bonus":       96,
                "msg":        "",
                "object":      "/d/dali/npc/hehongyao.c",
        ]),
        ([
                "id":          "gongzi",
                "name":        "πÛπ´◊”",
                "type":        "…±",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/dali/npc/guigongzi.c",
        ]),
        ([
                "id":          "shui niu",
                "name":        "ÀÆ≈£",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/dali/npc/cow.c",
        ]),
        ([
                "id":          "wu tiande",
                "name":        "Œ‚ÃÏµ¬",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/wutiande.c",
        ]),
        ([
                "id":          "tang huai",
                "name":        "Ã∆ª±",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/tanghuai.c",
        ]),
        ([
                "id":          "tang",
                "name":        "Ã∆’∆πÒ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/chengdu/npc/tanghua.c",
        ]),
        ([
                "id":          "tan youji",
                "name":        "Ã∑”—ºÕ",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/city/npc/shiye.c",
        ]),
        ([
                "id":          "shi song",
                "name":        " ∑À…",
                "type":        "…±",
                "bonus":       76,
                "msg":        "",
                "object":      "/d/city/npc/shisong.c",
        ]),
        ([
                "id":          "cui yuanwai",
                "name":        "¥ﬁ‘±Õ‚",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/city/npc/cui.c",
        ]),
        ([
                "id":          "cheng yaofa",
                "name":        "≥Ã“©∑¢",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/city/npc/cheng.c",
        ]),
        ([
                "id":          "zhang san",
                "name":        "’≈»˝",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/city/npc/baibian.c",
        ]),
        ([
                "id":          "liang xinglu",
                "name":        "¡∫–À¬ª",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/zhifu.c",
        ]),
        ([
                "id":          "li boyuan",
                "name":        "¿Ó≤©‘®",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/xueshi.c",
        ]),
        ([
                "id":          "tie gongji",
                "name":        "Ã˙π´º¶",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/tiegongji.c",
        ]),
        ([
                "id":          "tang",
                "name":        "ÃÀ◊” ÷",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/tang.c",
        ]),
        ([
                "id":          "shu chi",
                "name":        " È≥’",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/shuchi.c",
        ]),
        ([
                "id":          "chen jisheng",
                "name":        "≥¬ºÃ ¢",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/shiye.c",
        ]),
        ([
                "id":          "ling feixue",
                "name":        "¡Ë∑…—©",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/changan/npc/lingfeixue.c",
        ]),
        ([
                "id":          "qian laoben",
                "name":        "«Æ¿œ±æ",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/qianlaoben.c",
        ]),
        ([
                "id":          "lama",
                "name":        "¿Æ¬Ô",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/lama.c",
        ]),
        ([
                "id":          "feng jizhong",
                "name":        "∑Áº ÷–",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/beijing/npc/fengjizhong.c",
        ]),
        ([
                "id":          "qing",
                "name":        "–°«‡",
                "type":        "…±",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/baituo/npc/xiaoqing.c",
        ]),
        ([
                "id":          "trainer",
                "name":        "ΩÃ¡∑",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/baituo/npc/trainer.c",
        ]),
        ([
                "id":          "tiger",
                "name":        "¿œª¢",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/baituo/npc/tiger.c",
        ]),
        ([
                "id":          "snaker",
                "name":        "ŒË…ﬂ»À",
                "type":        "…±",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/baituo/npc/snaker.c",
        ]),
        ([
                "id":          "shanzei tou",
                "name":        "…Ω‘ÙÕ∑",
                "type":        "…±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/baituo/npc/shanzei3.c",
        ]),
        ([
                "id":          "playboy",
                "name":        "ª®ª®π´◊”",
                "type":        "…±",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/baituo/npc/playboy.c",
        ]),
        ([
                "id":          "men wei",
                "name":        "√≈Œ¿",
                "type":        "…±",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/baituo/npc/menwei.c",
        ]),
        ([
                "id":          "lion",
                "name":        "–€ ®",
                "type":        "…±",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/baituo/npc/lion.c",
        ]),
        ([
                "id":          "ge lunbu",
                "name":        "∏¬◊≤º",
                "type":        "…±",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/gelunbu.c",
        ]),
        ([
                "id":          "mo bushou",
                "name":        "ƒ™≤ª ’",
                "type":        "…±",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/mo-bu.c",
        ]),
});
mapping query_questsn()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
